/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'View_BangChietTinhGiangDay_RaDe_ChamThiLan1_NamHocHocKy' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase")]
	public abstract partial class ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// MaQuanLy : 
		/// </summary>
		private System.String		  _maQuanLy = string.Empty;
		
		/// <summary>
		/// MaLopHocPhan : 
		/// </summary>
		private System.String		  _maLopHocPhan = null;
		
		/// <summary>
		/// SoLuong : 
		/// </summary>
		private System.Int32?		  _soLuong = null;
		
		/// <summary>
		/// TietGiangDay : 
		/// </summary>
		private System.Int32		  _tietGiangDay = (int)0;
		
		/// <summary>
		/// HeSoLopDong : 
		/// </summary>
		private System.Decimal?		  _heSoLopDong = null;
		
		/// <summary>
		/// SoBaiDaCham : 
		/// </summary>
		private System.Int32		  _soBaiDaCham = (int)0;
		
		/// <summary>
		/// SoDeThiDapAn : 
		/// </summary>
		private System.Int32		  _soDeThiDapAn = (int)0;
		
		/// <summary>
		/// MaLopSinhVien : 
		/// </summary>
		private System.String		  _maLopSinhVien = string.Empty;
		
		/// <summary>
		/// TenLopSinhVien : 
		/// </summary>
		private System.String		  _tenLopSinhVien = null;
		
		/// <summary>
		/// HoTen : 
		/// </summary>
		private System.String		  _hoTen = null;
		
		/// <summary>
		/// NoiLamViec : 
		/// </summary>
		private System.String		  _noiLamViec = string.Empty;
		
		/// <summary>
		/// MaCoSo : 
		/// </summary>
		private System.String		  _maCoSo = string.Empty;
		
		/// <summary>
		/// TenCoSo : 
		/// </summary>
		private System.String		  _tenCoSo = string.Empty;
		
		/// <summary>
		/// MaHocVi : 
		/// </summary>
		private System.String		  _maHocVi = null;
		
		/// <summary>
		/// TenHocVi : 
		/// </summary>
		private System.String		  _tenHocVi = null;
		
		/// <summary>
		/// MaHocHam : 
		/// </summary>
		private System.String		  _maHocHam = null;
		
		/// <summary>
		/// TenHocHam : 
		/// </summary>
		private System.String		  _tenHocHam = null;
		
		/// <summary>
		/// HeSoTinChi : 
		/// </summary>
		private System.Decimal		  _heSoTinChi = 0.0m;
		
		/// <summary>
		/// DonGiaMotTiet : 
		/// </summary>
		private System.Decimal?		  _donGiaMotTiet = null;
		
		/// <summary>
		/// TienGiangDayTruocThue : 
		/// </summary>
		private System.Decimal?		  _tienGiangDayTruocThue = null;
		
		/// <summary>
		/// TienThueGiangDay : 
		/// </summary>
		private System.Decimal?		  _tienThueGiangDay = null;
		
		/// <summary>
		/// TienGiangDaySauThue : 
		/// </summary>
		private System.Decimal?		  _tienGiangDaySauThue = null;
		
		/// <summary>
		/// DonGiaChamThiChuan : 
		/// </summary>
		private System.Decimal?		  _donGiaChamThiChuan = null;
		
		/// <summary>
		/// TienChamThiTruocThue : 
		/// </summary>
		private System.Decimal?		  _tienChamThiTruocThue = null;
		
		/// <summary>
		/// TienThueChamThi : 
		/// </summary>
		private System.Decimal?		  _tienThueChamThi = null;
		
		/// <summary>
		/// TienChamThiSauThue : 
		/// </summary>
		private System.Decimal?		  _tienChamThiSauThue = null;
		
		/// <summary>
		/// DonGiaRaDeThiChuan : 
		/// </summary>
		private System.Decimal?		  _donGiaRaDeThiChuan = null;
		
		/// <summary>
		/// TienRaDeTruocThue : 
		/// </summary>
		private System.Decimal?		  _tienRaDeTruocThue = null;
		
		/// <summary>
		/// TienThueRaDe : 
		/// </summary>
		private System.Decimal?		  _tienThueRaDe = null;
		
		/// <summary>
		/// TienRaDeSauThue : 
		/// </summary>
		private System.Decimal?		  _tienRaDeSauThue = null;
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		private System.String		  _hocKy = string.Empty;
		
		/// <summary>
		/// TenHocKy : 
		/// </summary>
		private System.String		  _tenHocKy = null;
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		private System.String		  _namHoc = string.Empty;
		
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		private System.String		  _maMonHoc = string.Empty;
		
		/// <summary>
		/// TenMonHoc : 
		/// </summary>
		private System.String		  _tenMonHoc = string.Empty;
		
		/// <summary>
		/// TenLopHocPhan : 
		/// </summary>
		private System.String		  _tenLopHocPhan = string.Empty;
		
		/// <summary>
		/// TenHocPhan : 
		/// </summary>
		private System.String		  _tenHocPhan = string.Empty;
		
		/// <summary>
		/// MaBacDaoTao : 
		/// </summary>
		private System.String		  _maBacDaoTao = string.Empty;
		
		/// <summary>
		/// TenBacDaoTao : 
		/// </summary>
		private System.String		  _tenBacDaoTao = string.Empty;
		
		/// <summary>
		/// MaHeDaoTao : 
		/// </summary>
		private System.String		  _maHeDaoTao = string.Empty;
		
		/// <summary>
		/// TenHeDaoTao : 
		/// </summary>
		private System.String		  _tenHeDaoTao = string.Empty;
		
		/// <summary>
		/// SoLanDiLai : 
		/// </summary>
		private System.Decimal?		  _soLanDiLai = null;
		
		/// <summary>
		/// SoNgayLuuTru : 
		/// </summary>
		private System.Decimal?		  _soNgayLuuTru = null;
		
		/// <summary>
		/// ChiPhiDiLai : 
		/// </summary>
		private System.Decimal?		  _chiPhiDiLai = null;
		
		/// <summary>
		/// ChiPhiLuuTru : 
		/// </summary>
		private System.Decimal?		  _chiPhiLuuTru = null;
		
		/// <summary>
		/// TienLuuTruTruocThue : 
		/// </summary>
		private System.Decimal?		  _tienLuuTruTruocThue = null;
		
		/// <summary>
		/// TienThueLuuTru : 
		/// </summary>
		private System.Decimal?		  _tienThueLuuTru = null;
		
		/// <summary>
		/// TienLuuTruSauThue : 
		/// </summary>
		private System.Decimal?		  _tienLuuTruSauThue = null;
		
		/// <summary>
		/// TienDiLaiTruocThue : 
		/// </summary>
		private System.Decimal?		  _tienDiLaiTruocThue = null;
		
		/// <summary>
		/// TienThueDiLai : 
		/// </summary>
		private System.Decimal?		  _tienThueDiLai = null;
		
		/// <summary>
		/// TienDiLaiSauThue : 
		/// </summary>
		private System.Decimal?		  _tienDiLaiSauThue = null;
		
		/// <summary>
		/// HoanTat : 
		/// </summary>
		private System.Boolean		  _hoanTat = false;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> instance.
		///</summary>
		public ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> instance.
		///</summary>
		///<param name="_maQuanLy"></param>
		///<param name="_maLopHocPhan"></param>
		///<param name="_soLuong"></param>
		///<param name="_tietGiangDay"></param>
		///<param name="_heSoLopDong"></param>
		///<param name="_soBaiDaCham"></param>
		///<param name="_soDeThiDapAn"></param>
		///<param name="_maLopSinhVien"></param>
		///<param name="_tenLopSinhVien"></param>
		///<param name="_hoTen"></param>
		///<param name="_noiLamViec"></param>
		///<param name="_maCoSo"></param>
		///<param name="_tenCoSo"></param>
		///<param name="_maHocVi"></param>
		///<param name="_tenHocVi"></param>
		///<param name="_maHocHam"></param>
		///<param name="_tenHocHam"></param>
		///<param name="_heSoTinChi"></param>
		///<param name="_donGiaMotTiet"></param>
		///<param name="_tienGiangDayTruocThue"></param>
		///<param name="_tienThueGiangDay"></param>
		///<param name="_tienGiangDaySauThue"></param>
		///<param name="_donGiaChamThiChuan"></param>
		///<param name="_tienChamThiTruocThue"></param>
		///<param name="_tienThueChamThi"></param>
		///<param name="_tienChamThiSauThue"></param>
		///<param name="_donGiaRaDeThiChuan"></param>
		///<param name="_tienRaDeTruocThue"></param>
		///<param name="_tienThueRaDe"></param>
		///<param name="_tienRaDeSauThue"></param>
		///<param name="_hocKy"></param>
		///<param name="_tenHocKy"></param>
		///<param name="_namHoc"></param>
		///<param name="_maMonHoc"></param>
		///<param name="_tenMonHoc"></param>
		///<param name="_tenLopHocPhan"></param>
		///<param name="_tenHocPhan"></param>
		///<param name="_maBacDaoTao"></param>
		///<param name="_tenBacDaoTao"></param>
		///<param name="_maHeDaoTao"></param>
		///<param name="_tenHeDaoTao"></param>
		///<param name="_soLanDiLai"></param>
		///<param name="_soNgayLuuTru"></param>
		///<param name="_chiPhiDiLai"></param>
		///<param name="_chiPhiLuuTru"></param>
		///<param name="_tienLuuTruTruocThue"></param>
		///<param name="_tienThueLuuTru"></param>
		///<param name="_tienLuuTruSauThue"></param>
		///<param name="_tienDiLaiTruocThue"></param>
		///<param name="_tienThueDiLai"></param>
		///<param name="_tienDiLaiSauThue"></param>
		///<param name="_hoanTat"></param>
		public ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase(System.String _maQuanLy, System.String _maLopHocPhan, System.Int32? _soLuong, System.Int32 _tietGiangDay, System.Decimal? _heSoLopDong, System.Int32 _soBaiDaCham, System.Int32 _soDeThiDapAn, System.String _maLopSinhVien, System.String _tenLopSinhVien, System.String _hoTen, System.String _noiLamViec, System.String _maCoSo, System.String _tenCoSo, System.String _maHocVi, System.String _tenHocVi, System.String _maHocHam, System.String _tenHocHam, System.Decimal _heSoTinChi, System.Decimal? _donGiaMotTiet, System.Decimal? _tienGiangDayTruocThue, System.Decimal? _tienThueGiangDay, System.Decimal? _tienGiangDaySauThue, System.Decimal? _donGiaChamThiChuan, System.Decimal? _tienChamThiTruocThue, System.Decimal? _tienThueChamThi, System.Decimal? _tienChamThiSauThue, System.Decimal? _donGiaRaDeThiChuan, System.Decimal? _tienRaDeTruocThue, System.Decimal? _tienThueRaDe, System.Decimal? _tienRaDeSauThue, System.String _hocKy, System.String _tenHocKy, System.String _namHoc, System.String _maMonHoc, System.String _tenMonHoc, System.String _tenLopHocPhan, System.String _tenHocPhan, System.String _maBacDaoTao, System.String _tenBacDaoTao, System.String _maHeDaoTao, System.String _tenHeDaoTao, System.Decimal? _soLanDiLai, System.Decimal? _soNgayLuuTru, System.Decimal? _chiPhiDiLai, System.Decimal? _chiPhiLuuTru, System.Decimal? _tienLuuTruTruocThue, System.Decimal? _tienThueLuuTru, System.Decimal? _tienLuuTruSauThue, System.Decimal? _tienDiLaiTruocThue, System.Decimal? _tienThueDiLai, System.Decimal? _tienDiLaiSauThue, System.Boolean _hoanTat)
		{
			this._maQuanLy = _maQuanLy;
			this._maLopHocPhan = _maLopHocPhan;
			this._soLuong = _soLuong;
			this._tietGiangDay = _tietGiangDay;
			this._heSoLopDong = _heSoLopDong;
			this._soBaiDaCham = _soBaiDaCham;
			this._soDeThiDapAn = _soDeThiDapAn;
			this._maLopSinhVien = _maLopSinhVien;
			this._tenLopSinhVien = _tenLopSinhVien;
			this._hoTen = _hoTen;
			this._noiLamViec = _noiLamViec;
			this._maCoSo = _maCoSo;
			this._tenCoSo = _tenCoSo;
			this._maHocVi = _maHocVi;
			this._tenHocVi = _tenHocVi;
			this._maHocHam = _maHocHam;
			this._tenHocHam = _tenHocHam;
			this._heSoTinChi = _heSoTinChi;
			this._donGiaMotTiet = _donGiaMotTiet;
			this._tienGiangDayTruocThue = _tienGiangDayTruocThue;
			this._tienThueGiangDay = _tienThueGiangDay;
			this._tienGiangDaySauThue = _tienGiangDaySauThue;
			this._donGiaChamThiChuan = _donGiaChamThiChuan;
			this._tienChamThiTruocThue = _tienChamThiTruocThue;
			this._tienThueChamThi = _tienThueChamThi;
			this._tienChamThiSauThue = _tienChamThiSauThue;
			this._donGiaRaDeThiChuan = _donGiaRaDeThiChuan;
			this._tienRaDeTruocThue = _tienRaDeTruocThue;
			this._tienThueRaDe = _tienThueRaDe;
			this._tienRaDeSauThue = _tienRaDeSauThue;
			this._hocKy = _hocKy;
			this._tenHocKy = _tenHocKy;
			this._namHoc = _namHoc;
			this._maMonHoc = _maMonHoc;
			this._tenMonHoc = _tenMonHoc;
			this._tenLopHocPhan = _tenLopHocPhan;
			this._tenHocPhan = _tenHocPhan;
			this._maBacDaoTao = _maBacDaoTao;
			this._tenBacDaoTao = _tenBacDaoTao;
			this._maHeDaoTao = _maHeDaoTao;
			this._tenHeDaoTao = _tenHeDaoTao;
			this._soLanDiLai = _soLanDiLai;
			this._soNgayLuuTru = _soNgayLuuTru;
			this._chiPhiDiLai = _chiPhiDiLai;
			this._chiPhiLuuTru = _chiPhiLuuTru;
			this._tienLuuTruTruocThue = _tienLuuTruTruocThue;
			this._tienThueLuuTru = _tienThueLuuTru;
			this._tienLuuTruSauThue = _tienLuuTruSauThue;
			this._tienDiLaiTruocThue = _tienDiLaiTruocThue;
			this._tienThueDiLai = _tienThueDiLai;
			this._tienDiLaiSauThue = _tienDiLaiSauThue;
			this._hoanTat = _hoanTat;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy"/> instance.
		///</summary>
		///<param name="_maQuanLy"></param>
		///<param name="_maLopHocPhan"></param>
		///<param name="_soLuong"></param>
		///<param name="_tietGiangDay"></param>
		///<param name="_heSoLopDong"></param>
		///<param name="_soBaiDaCham"></param>
		///<param name="_soDeThiDapAn"></param>
		///<param name="_maLopSinhVien"></param>
		///<param name="_tenLopSinhVien"></param>
		///<param name="_hoTen"></param>
		///<param name="_noiLamViec"></param>
		///<param name="_maCoSo"></param>
		///<param name="_tenCoSo"></param>
		///<param name="_maHocVi"></param>
		///<param name="_tenHocVi"></param>
		///<param name="_maHocHam"></param>
		///<param name="_tenHocHam"></param>
		///<param name="_heSoTinChi"></param>
		///<param name="_donGiaMotTiet"></param>
		///<param name="_tienGiangDayTruocThue"></param>
		///<param name="_tienThueGiangDay"></param>
		///<param name="_tienGiangDaySauThue"></param>
		///<param name="_donGiaChamThiChuan"></param>
		///<param name="_tienChamThiTruocThue"></param>
		///<param name="_tienThueChamThi"></param>
		///<param name="_tienChamThiSauThue"></param>
		///<param name="_donGiaRaDeThiChuan"></param>
		///<param name="_tienRaDeTruocThue"></param>
		///<param name="_tienThueRaDe"></param>
		///<param name="_tienRaDeSauThue"></param>
		///<param name="_hocKy"></param>
		///<param name="_tenHocKy"></param>
		///<param name="_namHoc"></param>
		///<param name="_maMonHoc"></param>
		///<param name="_tenMonHoc"></param>
		///<param name="_tenLopHocPhan"></param>
		///<param name="_tenHocPhan"></param>
		///<param name="_maBacDaoTao"></param>
		///<param name="_tenBacDaoTao"></param>
		///<param name="_maHeDaoTao"></param>
		///<param name="_tenHeDaoTao"></param>
		///<param name="_soLanDiLai"></param>
		///<param name="_soNgayLuuTru"></param>
		///<param name="_chiPhiDiLai"></param>
		///<param name="_chiPhiLuuTru"></param>
		///<param name="_tienLuuTruTruocThue"></param>
		///<param name="_tienThueLuuTru"></param>
		///<param name="_tienLuuTruSauThue"></param>
		///<param name="_tienDiLaiTruocThue"></param>
		///<param name="_tienThueDiLai"></param>
		///<param name="_tienDiLaiSauThue"></param>
		///<param name="_hoanTat"></param>
		public static ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy CreateViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy(System.String _maQuanLy, System.String _maLopHocPhan, System.Int32? _soLuong, System.Int32 _tietGiangDay, System.Decimal? _heSoLopDong, System.Int32 _soBaiDaCham, System.Int32 _soDeThiDapAn, System.String _maLopSinhVien, System.String _tenLopSinhVien, System.String _hoTen, System.String _noiLamViec, System.String _maCoSo, System.String _tenCoSo, System.String _maHocVi, System.String _tenHocVi, System.String _maHocHam, System.String _tenHocHam, System.Decimal _heSoTinChi, System.Decimal? _donGiaMotTiet, System.Decimal? _tienGiangDayTruocThue, System.Decimal? _tienThueGiangDay, System.Decimal? _tienGiangDaySauThue, System.Decimal? _donGiaChamThiChuan, System.Decimal? _tienChamThiTruocThue, System.Decimal? _tienThueChamThi, System.Decimal? _tienChamThiSauThue, System.Decimal? _donGiaRaDeThiChuan, System.Decimal? _tienRaDeTruocThue, System.Decimal? _tienThueRaDe, System.Decimal? _tienRaDeSauThue, System.String _hocKy, System.String _tenHocKy, System.String _namHoc, System.String _maMonHoc, System.String _tenMonHoc, System.String _tenLopHocPhan, System.String _tenHocPhan, System.String _maBacDaoTao, System.String _tenBacDaoTao, System.String _maHeDaoTao, System.String _tenHeDaoTao, System.Decimal? _soLanDiLai, System.Decimal? _soNgayLuuTru, System.Decimal? _chiPhiDiLai, System.Decimal? _chiPhiLuuTru, System.Decimal? _tienLuuTruTruocThue, System.Decimal? _tienThueLuuTru, System.Decimal? _tienLuuTruSauThue, System.Decimal? _tienDiLaiTruocThue, System.Decimal? _tienThueDiLai, System.Decimal? _tienDiLaiSauThue, System.Boolean _hoanTat)
		{
			ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy = new ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy();
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaQuanLy = _maQuanLy;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaLopHocPhan = _maLopHocPhan;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.SoLuong = _soLuong;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TietGiangDay = _tietGiangDay;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.HeSoLopDong = _heSoLopDong;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.SoBaiDaCham = _soBaiDaCham;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.SoDeThiDapAn = _soDeThiDapAn;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaLopSinhVien = _maLopSinhVien;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenLopSinhVien = _tenLopSinhVien;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.HoTen = _hoTen;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.NoiLamViec = _noiLamViec;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaCoSo = _maCoSo;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenCoSo = _tenCoSo;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaHocVi = _maHocVi;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenHocVi = _tenHocVi;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaHocHam = _maHocHam;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenHocHam = _tenHocHam;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.HeSoTinChi = _heSoTinChi;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.DonGiaMotTiet = _donGiaMotTiet;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienGiangDayTruocThue = _tienGiangDayTruocThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienThueGiangDay = _tienThueGiangDay;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienGiangDaySauThue = _tienGiangDaySauThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.DonGiaChamThiChuan = _donGiaChamThiChuan;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienChamThiTruocThue = _tienChamThiTruocThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienThueChamThi = _tienThueChamThi;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienChamThiSauThue = _tienChamThiSauThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.DonGiaRaDeThiChuan = _donGiaRaDeThiChuan;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienRaDeTruocThue = _tienRaDeTruocThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienThueRaDe = _tienThueRaDe;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienRaDeSauThue = _tienRaDeSauThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.HocKy = _hocKy;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenHocKy = _tenHocKy;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.NamHoc = _namHoc;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaMonHoc = _maMonHoc;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenMonHoc = _tenMonHoc;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenLopHocPhan = _tenLopHocPhan;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenHocPhan = _tenHocPhan;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaBacDaoTao = _maBacDaoTao;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenBacDaoTao = _tenBacDaoTao;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.MaHeDaoTao = _maHeDaoTao;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TenHeDaoTao = _tenHeDaoTao;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.SoLanDiLai = _soLanDiLai;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.SoNgayLuuTru = _soNgayLuuTru;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.ChiPhiDiLai = _chiPhiDiLai;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.ChiPhiLuuTru = _chiPhiLuuTru;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienLuuTruTruocThue = _tienLuuTruTruocThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienThueLuuTru = _tienThueLuuTru;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienLuuTruSauThue = _tienLuuTruSauThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienDiLaiTruocThue = _tienDiLaiTruocThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienThueDiLai = _tienThueDiLai;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.TienDiLaiSauThue = _tienDiLaiSauThue;
			newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy.HoanTat = _hoanTat;
			return newViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the MaQuanLy property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaQuanLy
		{
			get
			{
				return this._maQuanLy; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaQuanLy does not allow null values.");
				if (_maQuanLy == value)
					return;
					
				this._maQuanLy = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaQuanLy");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaLopHocPhan property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaLopHocPhan
		{
			get
			{
				return this._maLopHocPhan; 
			}
			set
			{
				if (_maLopHocPhan == value)
					return;
					
				this._maLopHocPhan = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaLopHocPhan");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SoLuong property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsSoLuongNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32? SoLuong
		{
			get
			{
				return this._soLuong; 
			}
			set
			{
				if (_soLuong == value && SoLuong != null )
					return;
					
				this._soLuong = value;
				this._isDirty = true;
				
				OnPropertyChanged("SoLuong");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TietGiangDay property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32 TietGiangDay
		{
			get
			{
				return this._tietGiangDay; 
			}
			set
			{
				if (_tietGiangDay == value)
					return;
					
				this._tietGiangDay = value;
				this._isDirty = true;
				
				OnPropertyChanged("TietGiangDay");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the HeSoLopDong property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsHeSoLopDongNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? HeSoLopDong
		{
			get
			{
				return this._heSoLopDong; 
			}
			set
			{
				if (_heSoLopDong == value && HeSoLopDong != null )
					return;
					
				this._heSoLopDong = value;
				this._isDirty = true;
				
				OnPropertyChanged("HeSoLopDong");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SoBaiDaCham property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32 SoBaiDaCham
		{
			get
			{
				return this._soBaiDaCham; 
			}
			set
			{
				if (_soBaiDaCham == value)
					return;
					
				this._soBaiDaCham = value;
				this._isDirty = true;
				
				OnPropertyChanged("SoBaiDaCham");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SoDeThiDapAn property. 
		///		
		/// </summary>
		/// <value>This type is int</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Int32 SoDeThiDapAn
		{
			get
			{
				return this._soDeThiDapAn; 
			}
			set
			{
				if (_soDeThiDapAn == value)
					return;
					
				this._soDeThiDapAn = value;
				this._isDirty = true;
				
				OnPropertyChanged("SoDeThiDapAn");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaLopSinhVien property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaLopSinhVien
		{
			get
			{
				return this._maLopSinhVien; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaLopSinhVien does not allow null values.");
				if (_maLopSinhVien == value)
					return;
					
				this._maLopSinhVien = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaLopSinhVien");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenLopSinhVien property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenLopSinhVien
		{
			get
			{
				return this._tenLopSinhVien; 
			}
			set
			{
				if (_tenLopSinhVien == value)
					return;
					
				this._tenLopSinhVien = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenLopSinhVien");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the HoTen property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String HoTen
		{
			get
			{
				return this._hoTen; 
			}
			set
			{
				if (_hoTen == value)
					return;
					
				this._hoTen = value;
				this._isDirty = true;
				
				OnPropertyChanged("HoTen");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the NoiLamViec property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String NoiLamViec
		{
			get
			{
				return this._noiLamViec; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "NoiLamViec does not allow null values.");
				if (_noiLamViec == value)
					return;
					
				this._noiLamViec = value;
				this._isDirty = true;
				
				OnPropertyChanged("NoiLamViec");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaCoSo property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaCoSo
		{
			get
			{
				return this._maCoSo; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaCoSo does not allow null values.");
				if (_maCoSo == value)
					return;
					
				this._maCoSo = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaCoSo");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenCoSo property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenCoSo
		{
			get
			{
				return this._tenCoSo; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenCoSo does not allow null values.");
				if (_tenCoSo == value)
					return;
					
				this._tenCoSo = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenCoSo");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaHocVi property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaHocVi
		{
			get
			{
				return this._maHocVi; 
			}
			set
			{
				if (_maHocVi == value)
					return;
					
				this._maHocVi = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaHocVi");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenHocVi property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenHocVi
		{
			get
			{
				return this._tenHocVi; 
			}
			set
			{
				if (_tenHocVi == value)
					return;
					
				this._tenHocVi = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenHocVi");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaHocHam property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaHocHam
		{
			get
			{
				return this._maHocHam; 
			}
			set
			{
				if (_maHocHam == value)
					return;
					
				this._maHocHam = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaHocHam");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenHocHam property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenHocHam
		{
			get
			{
				return this._tenHocHam; 
			}
			set
			{
				if (_tenHocHam == value)
					return;
					
				this._tenHocHam = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenHocHam");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the HeSoTinChi property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal HeSoTinChi
		{
			get
			{
				return this._heSoTinChi; 
			}
			set
			{
				if (_heSoTinChi == value)
					return;
					
				this._heSoTinChi = value;
				this._isDirty = true;
				
				OnPropertyChanged("HeSoTinChi");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the DonGiaMotTiet property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsDonGiaMotTietNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? DonGiaMotTiet
		{
			get
			{
				return this._donGiaMotTiet; 
			}
			set
			{
				if (_donGiaMotTiet == value && DonGiaMotTiet != null )
					return;
					
				this._donGiaMotTiet = value;
				this._isDirty = true;
				
				OnPropertyChanged("DonGiaMotTiet");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienGiangDayTruocThue property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienGiangDayTruocThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienGiangDayTruocThue
		{
			get
			{
				return this._tienGiangDayTruocThue; 
			}
			set
			{
				if (_tienGiangDayTruocThue == value && TienGiangDayTruocThue != null )
					return;
					
				this._tienGiangDayTruocThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienGiangDayTruocThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienThueGiangDay property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienThueGiangDayNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienThueGiangDay
		{
			get
			{
				return this._tienThueGiangDay; 
			}
			set
			{
				if (_tienThueGiangDay == value && TienThueGiangDay != null )
					return;
					
				this._tienThueGiangDay = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienThueGiangDay");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienGiangDaySauThue property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienGiangDaySauThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienGiangDaySauThue
		{
			get
			{
				return this._tienGiangDaySauThue; 
			}
			set
			{
				if (_tienGiangDaySauThue == value && TienGiangDaySauThue != null )
					return;
					
				this._tienGiangDaySauThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienGiangDaySauThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the DonGiaChamThiChuan property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsDonGiaChamThiChuanNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? DonGiaChamThiChuan
		{
			get
			{
				return this._donGiaChamThiChuan; 
			}
			set
			{
				if (_donGiaChamThiChuan == value && DonGiaChamThiChuan != null )
					return;
					
				this._donGiaChamThiChuan = value;
				this._isDirty = true;
				
				OnPropertyChanged("DonGiaChamThiChuan");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienChamThiTruocThue property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienChamThiTruocThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienChamThiTruocThue
		{
			get
			{
				return this._tienChamThiTruocThue; 
			}
			set
			{
				if (_tienChamThiTruocThue == value && TienChamThiTruocThue != null )
					return;
					
				this._tienChamThiTruocThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienChamThiTruocThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienThueChamThi property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienThueChamThiNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienThueChamThi
		{
			get
			{
				return this._tienThueChamThi; 
			}
			set
			{
				if (_tienThueChamThi == value && TienThueChamThi != null )
					return;
					
				this._tienThueChamThi = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienThueChamThi");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienChamThiSauThue property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienChamThiSauThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienChamThiSauThue
		{
			get
			{
				return this._tienChamThiSauThue; 
			}
			set
			{
				if (_tienChamThiSauThue == value && TienChamThiSauThue != null )
					return;
					
				this._tienChamThiSauThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienChamThiSauThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the DonGiaRaDeThiChuan property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsDonGiaRaDeThiChuanNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? DonGiaRaDeThiChuan
		{
			get
			{
				return this._donGiaRaDeThiChuan; 
			}
			set
			{
				if (_donGiaRaDeThiChuan == value && DonGiaRaDeThiChuan != null )
					return;
					
				this._donGiaRaDeThiChuan = value;
				this._isDirty = true;
				
				OnPropertyChanged("DonGiaRaDeThiChuan");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienRaDeTruocThue property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienRaDeTruocThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienRaDeTruocThue
		{
			get
			{
				return this._tienRaDeTruocThue; 
			}
			set
			{
				if (_tienRaDeTruocThue == value && TienRaDeTruocThue != null )
					return;
					
				this._tienRaDeTruocThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienRaDeTruocThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienThueRaDe property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienThueRaDeNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienThueRaDe
		{
			get
			{
				return this._tienThueRaDe; 
			}
			set
			{
				if (_tienThueRaDe == value && TienThueRaDe != null )
					return;
					
				this._tienThueRaDe = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienThueRaDe");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienRaDeSauThue property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienRaDeSauThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienRaDeSauThue
		{
			get
			{
				return this._tienRaDeSauThue; 
			}
			set
			{
				if (_tienRaDeSauThue == value && TienRaDeSauThue != null )
					return;
					
				this._tienRaDeSauThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienRaDeSauThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the HocKy property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String HocKy
		{
			get
			{
				return this._hocKy; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "HocKy does not allow null values.");
				if (_hocKy == value)
					return;
					
				this._hocKy = value;
				this._isDirty = true;
				
				OnPropertyChanged("HocKy");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenHocKy property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenHocKy
		{
			get
			{
				return this._tenHocKy; 
			}
			set
			{
				if (_tenHocKy == value)
					return;
					
				this._tenHocKy = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenHocKy");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the NamHoc property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String NamHoc
		{
			get
			{
				return this._namHoc; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "NamHoc does not allow null values.");
				if (_namHoc == value)
					return;
					
				this._namHoc = value;
				this._isDirty = true;
				
				OnPropertyChanged("NamHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaMonHoc property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaMonHoc
		{
			get
			{
				return this._maMonHoc; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaMonHoc does not allow null values.");
				if (_maMonHoc == value)
					return;
					
				this._maMonHoc = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaMonHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenMonHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenMonHoc
		{
			get
			{
				return this._tenMonHoc; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenMonHoc does not allow null values.");
				if (_tenMonHoc == value)
					return;
					
				this._tenMonHoc = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenMonHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenLopHocPhan property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenLopHocPhan
		{
			get
			{
				return this._tenLopHocPhan; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenLopHocPhan does not allow null values.");
				if (_tenLopHocPhan == value)
					return;
					
				this._tenLopHocPhan = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenLopHocPhan");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenHocPhan property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenHocPhan
		{
			get
			{
				return this._tenHocPhan; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenHocPhan does not allow null values.");
				if (_tenHocPhan == value)
					return;
					
				this._tenHocPhan = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenHocPhan");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaBacDaoTao property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaBacDaoTao
		{
			get
			{
				return this._maBacDaoTao; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaBacDaoTao does not allow null values.");
				if (_maBacDaoTao == value)
					return;
					
				this._maBacDaoTao = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaBacDaoTao");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenBacDaoTao property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenBacDaoTao
		{
			get
			{
				return this._tenBacDaoTao; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenBacDaoTao does not allow null values.");
				if (_tenBacDaoTao == value)
					return;
					
				this._tenBacDaoTao = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenBacDaoTao");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the MaHeDaoTao property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaHeDaoTao
		{
			get
			{
				return this._maHeDaoTao; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaHeDaoTao does not allow null values.");
				if (_maHeDaoTao == value)
					return;
					
				this._maHeDaoTao = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaHeDaoTao");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenHeDaoTao property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenHeDaoTao
		{
			get
			{
				return this._tenHeDaoTao; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenHeDaoTao does not allow null values.");
				if (_tenHeDaoTao == value)
					return;
					
				this._tenHeDaoTao = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenHeDaoTao");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SoLanDiLai property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsSoLanDiLaiNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? SoLanDiLai
		{
			get
			{
				return this._soLanDiLai; 
			}
			set
			{
				if (_soLanDiLai == value && SoLanDiLai != null )
					return;
					
				this._soLanDiLai = value;
				this._isDirty = true;
				
				OnPropertyChanged("SoLanDiLai");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the SoNgayLuuTru property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsSoNgayLuuTruNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? SoNgayLuuTru
		{
			get
			{
				return this._soNgayLuuTru; 
			}
			set
			{
				if (_soNgayLuuTru == value && SoNgayLuuTru != null )
					return;
					
				this._soNgayLuuTru = value;
				this._isDirty = true;
				
				OnPropertyChanged("SoNgayLuuTru");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ChiPhiDiLai property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsChiPhiDiLaiNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? ChiPhiDiLai
		{
			get
			{
				return this._chiPhiDiLai; 
			}
			set
			{
				if (_chiPhiDiLai == value && ChiPhiDiLai != null )
					return;
					
				this._chiPhiDiLai = value;
				this._isDirty = true;
				
				OnPropertyChanged("ChiPhiDiLai");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the ChiPhiLuuTru property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsChiPhiLuuTruNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? ChiPhiLuuTru
		{
			get
			{
				return this._chiPhiLuuTru; 
			}
			set
			{
				if (_chiPhiLuuTru == value && ChiPhiLuuTru != null )
					return;
					
				this._chiPhiLuuTru = value;
				this._isDirty = true;
				
				OnPropertyChanged("ChiPhiLuuTru");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienLuuTruTruocThue property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienLuuTruTruocThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienLuuTruTruocThue
		{
			get
			{
				return this._tienLuuTruTruocThue; 
			}
			set
			{
				if (_tienLuuTruTruocThue == value && TienLuuTruTruocThue != null )
					return;
					
				this._tienLuuTruTruocThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienLuuTruTruocThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienThueLuuTru property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienThueLuuTruNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienThueLuuTru
		{
			get
			{
				return this._tienThueLuuTru; 
			}
			set
			{
				if (_tienThueLuuTru == value && TienThueLuuTru != null )
					return;
					
				this._tienThueLuuTru = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienThueLuuTru");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienLuuTruSauThue property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienLuuTruSauThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienLuuTruSauThue
		{
			get
			{
				return this._tienLuuTruSauThue; 
			}
			set
			{
				if (_tienLuuTruSauThue == value && TienLuuTruSauThue != null )
					return;
					
				this._tienLuuTruSauThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienLuuTruSauThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienDiLaiTruocThue property. 
		///		
		/// </summary>
		/// <value>This type is decimal</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienDiLaiTruocThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienDiLaiTruocThue
		{
			get
			{
				return this._tienDiLaiTruocThue; 
			}
			set
			{
				if (_tienDiLaiTruocThue == value && TienDiLaiTruocThue != null )
					return;
					
				this._tienDiLaiTruocThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienDiLaiTruocThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienThueDiLai property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienThueDiLaiNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienThueDiLai
		{
			get
			{
				return this._tienThueDiLai; 
			}
			set
			{
				if (_tienThueDiLai == value && TienThueDiLai != null )
					return;
					
				this._tienThueDiLai = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienThueDiLai");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TienDiLaiSauThue property. 
		///		
		/// </summary>
		/// <value>This type is numeric</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsTienDiLaiSauThueNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Decimal? TienDiLaiSauThue
		{
			get
			{
				return this._tienDiLaiSauThue; 
			}
			set
			{
				if (_tienDiLaiSauThue == value && TienDiLaiSauThue != null )
					return;
					
				this._tienDiLaiSauThue = value;
				this._isDirty = true;
				
				OnPropertyChanged("TienDiLaiSauThue");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the HoanTat property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean HoanTat
		{
			get
			{
				return this._hoanTat; 
			}
			set
			{
				if (_hoanTat == value)
					return;
					
				this._hoanTat = value;
				this._isDirty = true;
				
				OnPropertyChanged("HoanTat");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "View_BangChietTinhGiangDay_RaDe_ChamThiLan1_NamHocHocKy"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase Entity 
		///</summary>
		public virtual ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase Copy()
		{
			//shallow copy entity
			ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy copy = new ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy();
				copy.MaQuanLy = this.MaQuanLy;
				copy.MaLopHocPhan = this.MaLopHocPhan;
				copy.SoLuong = this.SoLuong;
				copy.TietGiangDay = this.TietGiangDay;
				copy.HeSoLopDong = this.HeSoLopDong;
				copy.SoBaiDaCham = this.SoBaiDaCham;
				copy.SoDeThiDapAn = this.SoDeThiDapAn;
				copy.MaLopSinhVien = this.MaLopSinhVien;
				copy.TenLopSinhVien = this.TenLopSinhVien;
				copy.HoTen = this.HoTen;
				copy.NoiLamViec = this.NoiLamViec;
				copy.MaCoSo = this.MaCoSo;
				copy.TenCoSo = this.TenCoSo;
				copy.MaHocVi = this.MaHocVi;
				copy.TenHocVi = this.TenHocVi;
				copy.MaHocHam = this.MaHocHam;
				copy.TenHocHam = this.TenHocHam;
				copy.HeSoTinChi = this.HeSoTinChi;
				copy.DonGiaMotTiet = this.DonGiaMotTiet;
				copy.TienGiangDayTruocThue = this.TienGiangDayTruocThue;
				copy.TienThueGiangDay = this.TienThueGiangDay;
				copy.TienGiangDaySauThue = this.TienGiangDaySauThue;
				copy.DonGiaChamThiChuan = this.DonGiaChamThiChuan;
				copy.TienChamThiTruocThue = this.TienChamThiTruocThue;
				copy.TienThueChamThi = this.TienThueChamThi;
				copy.TienChamThiSauThue = this.TienChamThiSauThue;
				copy.DonGiaRaDeThiChuan = this.DonGiaRaDeThiChuan;
				copy.TienRaDeTruocThue = this.TienRaDeTruocThue;
				copy.TienThueRaDe = this.TienThueRaDe;
				copy.TienRaDeSauThue = this.TienRaDeSauThue;
				copy.HocKy = this.HocKy;
				copy.TenHocKy = this.TenHocKy;
				copy.NamHoc = this.NamHoc;
				copy.MaMonHoc = this.MaMonHoc;
				copy.TenMonHoc = this.TenMonHoc;
				copy.TenLopHocPhan = this.TenLopHocPhan;
				copy.TenHocPhan = this.TenHocPhan;
				copy.MaBacDaoTao = this.MaBacDaoTao;
				copy.TenBacDaoTao = this.TenBacDaoTao;
				copy.MaHeDaoTao = this.MaHeDaoTao;
				copy.TenHeDaoTao = this.TenHeDaoTao;
				copy.SoLanDiLai = this.SoLanDiLai;
				copy.SoNgayLuuTru = this.SoNgayLuuTru;
				copy.ChiPhiDiLai = this.ChiPhiDiLai;
				copy.ChiPhiLuuTru = this.ChiPhiLuuTru;
				copy.TienLuuTruTruocThue = this.TienLuuTruTruocThue;
				copy.TienThueLuuTru = this.TienThueLuuTru;
				copy.TienLuuTruSauThue = this.TienLuuTruSauThue;
				copy.TienDiLaiTruocThue = this.TienDiLaiTruocThue;
				copy.TienThueDiLai = this.TienThueDiLai;
				copy.TienDiLaiSauThue = this.TienDiLaiSauThue;
				copy.HoanTat = this.HoanTat;
			copy.AcceptChanges();
			return (ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase Object1, ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.MaQuanLy != Object2.MaQuanLy)
				equal = false;
			if (Object1.MaLopHocPhan != null && Object2.MaLopHocPhan != null )
			{
				if (Object1.MaLopHocPhan != Object2.MaLopHocPhan)
					equal = false;
			}
			else if (Object1.MaLopHocPhan == null ^ Object1.MaLopHocPhan == null )
			{
				equal = false;
			}
			if (Object1.SoLuong != null && Object2.SoLuong != null )
			{
				if (Object1.SoLuong != Object2.SoLuong)
					equal = false;
			}
			else if (Object1.SoLuong == null ^ Object1.SoLuong == null )
			{
				equal = false;
			}
			if (Object1.TietGiangDay != Object2.TietGiangDay)
				equal = false;
			if (Object1.HeSoLopDong != null && Object2.HeSoLopDong != null )
			{
				if (Object1.HeSoLopDong != Object2.HeSoLopDong)
					equal = false;
			}
			else if (Object1.HeSoLopDong == null ^ Object1.HeSoLopDong == null )
			{
				equal = false;
			}
			if (Object1.SoBaiDaCham != Object2.SoBaiDaCham)
				equal = false;
			if (Object1.SoDeThiDapAn != Object2.SoDeThiDapAn)
				equal = false;
			if (Object1.MaLopSinhVien != Object2.MaLopSinhVien)
				equal = false;
			if (Object1.TenLopSinhVien != null && Object2.TenLopSinhVien != null )
			{
				if (Object1.TenLopSinhVien != Object2.TenLopSinhVien)
					equal = false;
			}
			else if (Object1.TenLopSinhVien == null ^ Object1.TenLopSinhVien == null )
			{
				equal = false;
			}
			if (Object1.HoTen != null && Object2.HoTen != null )
			{
				if (Object1.HoTen != Object2.HoTen)
					equal = false;
			}
			else if (Object1.HoTen == null ^ Object1.HoTen == null )
			{
				equal = false;
			}
			if (Object1.NoiLamViec != Object2.NoiLamViec)
				equal = false;
			if (Object1.MaCoSo != Object2.MaCoSo)
				equal = false;
			if (Object1.TenCoSo != Object2.TenCoSo)
				equal = false;
			if (Object1.MaHocVi != null && Object2.MaHocVi != null )
			{
				if (Object1.MaHocVi != Object2.MaHocVi)
					equal = false;
			}
			else if (Object1.MaHocVi == null ^ Object1.MaHocVi == null )
			{
				equal = false;
			}
			if (Object1.TenHocVi != null && Object2.TenHocVi != null )
			{
				if (Object1.TenHocVi != Object2.TenHocVi)
					equal = false;
			}
			else if (Object1.TenHocVi == null ^ Object1.TenHocVi == null )
			{
				equal = false;
			}
			if (Object1.MaHocHam != null && Object2.MaHocHam != null )
			{
				if (Object1.MaHocHam != Object2.MaHocHam)
					equal = false;
			}
			else if (Object1.MaHocHam == null ^ Object1.MaHocHam == null )
			{
				equal = false;
			}
			if (Object1.TenHocHam != null && Object2.TenHocHam != null )
			{
				if (Object1.TenHocHam != Object2.TenHocHam)
					equal = false;
			}
			else if (Object1.TenHocHam == null ^ Object1.TenHocHam == null )
			{
				equal = false;
			}
			if (Object1.HeSoTinChi != Object2.HeSoTinChi)
				equal = false;
			if (Object1.DonGiaMotTiet != null && Object2.DonGiaMotTiet != null )
			{
				if (Object1.DonGiaMotTiet != Object2.DonGiaMotTiet)
					equal = false;
			}
			else if (Object1.DonGiaMotTiet == null ^ Object1.DonGiaMotTiet == null )
			{
				equal = false;
			}
			if (Object1.TienGiangDayTruocThue != null && Object2.TienGiangDayTruocThue != null )
			{
				if (Object1.TienGiangDayTruocThue != Object2.TienGiangDayTruocThue)
					equal = false;
			}
			else if (Object1.TienGiangDayTruocThue == null ^ Object1.TienGiangDayTruocThue == null )
			{
				equal = false;
			}
			if (Object1.TienThueGiangDay != null && Object2.TienThueGiangDay != null )
			{
				if (Object1.TienThueGiangDay != Object2.TienThueGiangDay)
					equal = false;
			}
			else if (Object1.TienThueGiangDay == null ^ Object1.TienThueGiangDay == null )
			{
				equal = false;
			}
			if (Object1.TienGiangDaySauThue != null && Object2.TienGiangDaySauThue != null )
			{
				if (Object1.TienGiangDaySauThue != Object2.TienGiangDaySauThue)
					equal = false;
			}
			else if (Object1.TienGiangDaySauThue == null ^ Object1.TienGiangDaySauThue == null )
			{
				equal = false;
			}
			if (Object1.DonGiaChamThiChuan != null && Object2.DonGiaChamThiChuan != null )
			{
				if (Object1.DonGiaChamThiChuan != Object2.DonGiaChamThiChuan)
					equal = false;
			}
			else if (Object1.DonGiaChamThiChuan == null ^ Object1.DonGiaChamThiChuan == null )
			{
				equal = false;
			}
			if (Object1.TienChamThiTruocThue != null && Object2.TienChamThiTruocThue != null )
			{
				if (Object1.TienChamThiTruocThue != Object2.TienChamThiTruocThue)
					equal = false;
			}
			else if (Object1.TienChamThiTruocThue == null ^ Object1.TienChamThiTruocThue == null )
			{
				equal = false;
			}
			if (Object1.TienThueChamThi != null && Object2.TienThueChamThi != null )
			{
				if (Object1.TienThueChamThi != Object2.TienThueChamThi)
					equal = false;
			}
			else if (Object1.TienThueChamThi == null ^ Object1.TienThueChamThi == null )
			{
				equal = false;
			}
			if (Object1.TienChamThiSauThue != null && Object2.TienChamThiSauThue != null )
			{
				if (Object1.TienChamThiSauThue != Object2.TienChamThiSauThue)
					equal = false;
			}
			else if (Object1.TienChamThiSauThue == null ^ Object1.TienChamThiSauThue == null )
			{
				equal = false;
			}
			if (Object1.DonGiaRaDeThiChuan != null && Object2.DonGiaRaDeThiChuan != null )
			{
				if (Object1.DonGiaRaDeThiChuan != Object2.DonGiaRaDeThiChuan)
					equal = false;
			}
			else if (Object1.DonGiaRaDeThiChuan == null ^ Object1.DonGiaRaDeThiChuan == null )
			{
				equal = false;
			}
			if (Object1.TienRaDeTruocThue != null && Object2.TienRaDeTruocThue != null )
			{
				if (Object1.TienRaDeTruocThue != Object2.TienRaDeTruocThue)
					equal = false;
			}
			else if (Object1.TienRaDeTruocThue == null ^ Object1.TienRaDeTruocThue == null )
			{
				equal = false;
			}
			if (Object1.TienThueRaDe != null && Object2.TienThueRaDe != null )
			{
				if (Object1.TienThueRaDe != Object2.TienThueRaDe)
					equal = false;
			}
			else if (Object1.TienThueRaDe == null ^ Object1.TienThueRaDe == null )
			{
				equal = false;
			}
			if (Object1.TienRaDeSauThue != null && Object2.TienRaDeSauThue != null )
			{
				if (Object1.TienRaDeSauThue != Object2.TienRaDeSauThue)
					equal = false;
			}
			else if (Object1.TienRaDeSauThue == null ^ Object1.TienRaDeSauThue == null )
			{
				equal = false;
			}
			if (Object1.HocKy != Object2.HocKy)
				equal = false;
			if (Object1.TenHocKy != null && Object2.TenHocKy != null )
			{
				if (Object1.TenHocKy != Object2.TenHocKy)
					equal = false;
			}
			else if (Object1.TenHocKy == null ^ Object1.TenHocKy == null )
			{
				equal = false;
			}
			if (Object1.NamHoc != Object2.NamHoc)
				equal = false;
			if (Object1.MaMonHoc != Object2.MaMonHoc)
				equal = false;
			if (Object1.TenMonHoc != Object2.TenMonHoc)
				equal = false;
			if (Object1.TenLopHocPhan != Object2.TenLopHocPhan)
				equal = false;
			if (Object1.TenHocPhan != Object2.TenHocPhan)
				equal = false;
			if (Object1.MaBacDaoTao != Object2.MaBacDaoTao)
				equal = false;
			if (Object1.TenBacDaoTao != Object2.TenBacDaoTao)
				equal = false;
			if (Object1.MaHeDaoTao != Object2.MaHeDaoTao)
				equal = false;
			if (Object1.TenHeDaoTao != Object2.TenHeDaoTao)
				equal = false;
			if (Object1.SoLanDiLai != null && Object2.SoLanDiLai != null )
			{
				if (Object1.SoLanDiLai != Object2.SoLanDiLai)
					equal = false;
			}
			else if (Object1.SoLanDiLai == null ^ Object1.SoLanDiLai == null )
			{
				equal = false;
			}
			if (Object1.SoNgayLuuTru != null && Object2.SoNgayLuuTru != null )
			{
				if (Object1.SoNgayLuuTru != Object2.SoNgayLuuTru)
					equal = false;
			}
			else if (Object1.SoNgayLuuTru == null ^ Object1.SoNgayLuuTru == null )
			{
				equal = false;
			}
			if (Object1.ChiPhiDiLai != null && Object2.ChiPhiDiLai != null )
			{
				if (Object1.ChiPhiDiLai != Object2.ChiPhiDiLai)
					equal = false;
			}
			else if (Object1.ChiPhiDiLai == null ^ Object1.ChiPhiDiLai == null )
			{
				equal = false;
			}
			if (Object1.ChiPhiLuuTru != null && Object2.ChiPhiLuuTru != null )
			{
				if (Object1.ChiPhiLuuTru != Object2.ChiPhiLuuTru)
					equal = false;
			}
			else if (Object1.ChiPhiLuuTru == null ^ Object1.ChiPhiLuuTru == null )
			{
				equal = false;
			}
			if (Object1.TienLuuTruTruocThue != null && Object2.TienLuuTruTruocThue != null )
			{
				if (Object1.TienLuuTruTruocThue != Object2.TienLuuTruTruocThue)
					equal = false;
			}
			else if (Object1.TienLuuTruTruocThue == null ^ Object1.TienLuuTruTruocThue == null )
			{
				equal = false;
			}
			if (Object1.TienThueLuuTru != null && Object2.TienThueLuuTru != null )
			{
				if (Object1.TienThueLuuTru != Object2.TienThueLuuTru)
					equal = false;
			}
			else if (Object1.TienThueLuuTru == null ^ Object1.TienThueLuuTru == null )
			{
				equal = false;
			}
			if (Object1.TienLuuTruSauThue != null && Object2.TienLuuTruSauThue != null )
			{
				if (Object1.TienLuuTruSauThue != Object2.TienLuuTruSauThue)
					equal = false;
			}
			else if (Object1.TienLuuTruSauThue == null ^ Object1.TienLuuTruSauThue == null )
			{
				equal = false;
			}
			if (Object1.TienDiLaiTruocThue != null && Object2.TienDiLaiTruocThue != null )
			{
				if (Object1.TienDiLaiTruocThue != Object2.TienDiLaiTruocThue)
					equal = false;
			}
			else if (Object1.TienDiLaiTruocThue == null ^ Object1.TienDiLaiTruocThue == null )
			{
				equal = false;
			}
			if (Object1.TienThueDiLai != null && Object2.TienThueDiLai != null )
			{
				if (Object1.TienThueDiLai != Object2.TienThueDiLai)
					equal = false;
			}
			else if (Object1.TienThueDiLai == null ^ Object1.TienThueDiLai == null )
			{
				equal = false;
			}
			if (Object1.TienDiLaiSauThue != null && Object2.TienDiLaiSauThue != null )
			{
				if (Object1.TienDiLaiSauThue != Object2.TienDiLaiSauThue)
					equal = false;
			}
			else if (Object1.TienDiLaiSauThue == null ^ Object1.TienDiLaiSauThue == null )
			{
				equal = false;
			}
			if (Object1.HoanTat != Object2.HoanTat)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy entity, string propertyName)
		{
			switch (propertyName)
			{
				case "MaQuanLy":
					return entity.MaQuanLy;
				case "MaLopHocPhan":
					return entity.MaLopHocPhan;
				case "SoLuong":
					return entity.SoLuong;
				case "TietGiangDay":
					return entity.TietGiangDay;
				case "HeSoLopDong":
					return entity.HeSoLopDong;
				case "SoBaiDaCham":
					return entity.SoBaiDaCham;
				case "SoDeThiDapAn":
					return entity.SoDeThiDapAn;
				case "MaLopSinhVien":
					return entity.MaLopSinhVien;
				case "TenLopSinhVien":
					return entity.TenLopSinhVien;
				case "HoTen":
					return entity.HoTen;
				case "NoiLamViec":
					return entity.NoiLamViec;
				case "MaCoSo":
					return entity.MaCoSo;
				case "TenCoSo":
					return entity.TenCoSo;
				case "MaHocVi":
					return entity.MaHocVi;
				case "TenHocVi":
					return entity.TenHocVi;
				case "MaHocHam":
					return entity.MaHocHam;
				case "TenHocHam":
					return entity.TenHocHam;
				case "HeSoTinChi":
					return entity.HeSoTinChi;
				case "DonGiaMotTiet":
					return entity.DonGiaMotTiet;
				case "TienGiangDayTruocThue":
					return entity.TienGiangDayTruocThue;
				case "TienThueGiangDay":
					return entity.TienThueGiangDay;
				case "TienGiangDaySauThue":
					return entity.TienGiangDaySauThue;
				case "DonGiaChamThiChuan":
					return entity.DonGiaChamThiChuan;
				case "TienChamThiTruocThue":
					return entity.TienChamThiTruocThue;
				case "TienThueChamThi":
					return entity.TienThueChamThi;
				case "TienChamThiSauThue":
					return entity.TienChamThiSauThue;
				case "DonGiaRaDeThiChuan":
					return entity.DonGiaRaDeThiChuan;
				case "TienRaDeTruocThue":
					return entity.TienRaDeTruocThue;
				case "TienThueRaDe":
					return entity.TienThueRaDe;
				case "TienRaDeSauThue":
					return entity.TienRaDeSauThue;
				case "HocKy":
					return entity.HocKy;
				case "TenHocKy":
					return entity.TenHocKy;
				case "NamHoc":
					return entity.NamHoc;
				case "MaMonHoc":
					return entity.MaMonHoc;
				case "TenMonHoc":
					return entity.TenMonHoc;
				case "TenLopHocPhan":
					return entity.TenLopHocPhan;
				case "TenHocPhan":
					return entity.TenHocPhan;
				case "MaBacDaoTao":
					return entity.MaBacDaoTao;
				case "TenBacDaoTao":
					return entity.TenBacDaoTao;
				case "MaHeDaoTao":
					return entity.MaHeDaoTao;
				case "TenHeDaoTao":
					return entity.TenHeDaoTao;
				case "SoLanDiLai":
					return entity.SoLanDiLai;
				case "SoNgayLuuTru":
					return entity.SoNgayLuuTru;
				case "ChiPhiDiLai":
					return entity.ChiPhiDiLai;
				case "ChiPhiLuuTru":
					return entity.ChiPhiLuuTru;
				case "TienLuuTruTruocThue":
					return entity.TienLuuTruTruocThue;
				case "TienThueLuuTru":
					return entity.TienThueLuuTru;
				case "TienLuuTruSauThue":
					return entity.TienLuuTruSauThue;
				case "TienDiLaiTruocThue":
					return entity.TienDiLaiTruocThue;
				case "TienThueDiLai":
					return entity.TienThueDiLai;
				case "TienDiLaiSauThue":
					return entity.TienDiLaiSauThue;
				case "HoanTat":
					return entity.HoanTat;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{53}{52}- MaQuanLy: {0}{52}- MaLopHocPhan: {1}{52}- SoLuong: {2}{52}- TietGiangDay: {3}{52}- HeSoLopDong: {4}{52}- SoBaiDaCham: {5}{52}- SoDeThiDapAn: {6}{52}- MaLopSinhVien: {7}{52}- TenLopSinhVien: {8}{52}- HoTen: {9}{52}- NoiLamViec: {10}{52}- MaCoSo: {11}{52}- TenCoSo: {12}{52}- MaHocVi: {13}{52}- TenHocVi: {14}{52}- MaHocHam: {15}{52}- TenHocHam: {16}{52}- HeSoTinChi: {17}{52}- DonGiaMotTiet: {18}{52}- TienGiangDayTruocThue: {19}{52}- TienThueGiangDay: {20}{52}- TienGiangDaySauThue: {21}{52}- DonGiaChamThiChuan: {22}{52}- TienChamThiTruocThue: {23}{52}- TienThueChamThi: {24}{52}- TienChamThiSauThue: {25}{52}- DonGiaRaDeThiChuan: {26}{52}- TienRaDeTruocThue: {27}{52}- TienThueRaDe: {28}{52}- TienRaDeSauThue: {29}{52}- HocKy: {30}{52}- TenHocKy: {31}{52}- NamHoc: {32}{52}- MaMonHoc: {33}{52}- TenMonHoc: {34}{52}- TenLopHocPhan: {35}{52}- TenHocPhan: {36}{52}- MaBacDaoTao: {37}{52}- TenBacDaoTao: {38}{52}- MaHeDaoTao: {39}{52}- TenHeDaoTao: {40}{52}- SoLanDiLai: {41}{52}- SoNgayLuuTru: {42}{52}- ChiPhiDiLai: {43}{52}- ChiPhiLuuTru: {44}{52}- TienLuuTruTruocThue: {45}{52}- TienThueLuuTru: {46}{52}- TienLuuTruSauThue: {47}{52}- TienDiLaiTruocThue: {48}{52}- TienThueDiLai: {49}{52}- TienDiLaiSauThue: {50}{52}- HoanTat: {51}{52}", 
				this.MaQuanLy,
				(this.MaLopHocPhan == null) ? string.Empty : this.MaLopHocPhan.ToString(),
			     
				(this.SoLuong == null) ? string.Empty : this.SoLuong.ToString(),
			     
				this.TietGiangDay,
				(this.HeSoLopDong == null) ? string.Empty : this.HeSoLopDong.ToString(),
			     
				this.SoBaiDaCham,
				this.SoDeThiDapAn,
				this.MaLopSinhVien,
				(this.TenLopSinhVien == null) ? string.Empty : this.TenLopSinhVien.ToString(),
			     
				(this.HoTen == null) ? string.Empty : this.HoTen.ToString(),
			     
				this.NoiLamViec,
				this.MaCoSo,
				this.TenCoSo,
				(this.MaHocVi == null) ? string.Empty : this.MaHocVi.ToString(),
			     
				(this.TenHocVi == null) ? string.Empty : this.TenHocVi.ToString(),
			     
				(this.MaHocHam == null) ? string.Empty : this.MaHocHam.ToString(),
			     
				(this.TenHocHam == null) ? string.Empty : this.TenHocHam.ToString(),
			     
				this.HeSoTinChi,
				(this.DonGiaMotTiet == null) ? string.Empty : this.DonGiaMotTiet.ToString(),
			     
				(this.TienGiangDayTruocThue == null) ? string.Empty : this.TienGiangDayTruocThue.ToString(),
			     
				(this.TienThueGiangDay == null) ? string.Empty : this.TienThueGiangDay.ToString(),
			     
				(this.TienGiangDaySauThue == null) ? string.Empty : this.TienGiangDaySauThue.ToString(),
			     
				(this.DonGiaChamThiChuan == null) ? string.Empty : this.DonGiaChamThiChuan.ToString(),
			     
				(this.TienChamThiTruocThue == null) ? string.Empty : this.TienChamThiTruocThue.ToString(),
			     
				(this.TienThueChamThi == null) ? string.Empty : this.TienThueChamThi.ToString(),
			     
				(this.TienChamThiSauThue == null) ? string.Empty : this.TienChamThiSauThue.ToString(),
			     
				(this.DonGiaRaDeThiChuan == null) ? string.Empty : this.DonGiaRaDeThiChuan.ToString(),
			     
				(this.TienRaDeTruocThue == null) ? string.Empty : this.TienRaDeTruocThue.ToString(),
			     
				(this.TienThueRaDe == null) ? string.Empty : this.TienThueRaDe.ToString(),
			     
				(this.TienRaDeSauThue == null) ? string.Empty : this.TienRaDeSauThue.ToString(),
			     
				this.HocKy,
				(this.TenHocKy == null) ? string.Empty : this.TenHocKy.ToString(),
			     
				this.NamHoc,
				this.MaMonHoc,
				this.TenMonHoc,
				this.TenLopHocPhan,
				this.TenHocPhan,
				this.MaBacDaoTao,
				this.TenBacDaoTao,
				this.MaHeDaoTao,
				this.TenHeDaoTao,
				(this.SoLanDiLai == null) ? string.Empty : this.SoLanDiLai.ToString(),
			     
				(this.SoNgayLuuTru == null) ? string.Empty : this.SoNgayLuuTru.ToString(),
			     
				(this.ChiPhiDiLai == null) ? string.Empty : this.ChiPhiDiLai.ToString(),
			     
				(this.ChiPhiLuuTru == null) ? string.Empty : this.ChiPhiLuuTru.ToString(),
			     
				(this.TienLuuTruTruocThue == null) ? string.Empty : this.TienLuuTruTruocThue.ToString(),
			     
				(this.TienThueLuuTru == null) ? string.Empty : this.TienThueLuuTru.ToString(),
			     
				(this.TienLuuTruSauThue == null) ? string.Empty : this.TienLuuTruSauThue.ToString(),
			     
				(this.TienDiLaiTruocThue == null) ? string.Empty : this.TienDiLaiTruocThue.ToString(),
			     
				(this.TienThueDiLai == null) ? string.Empty : this.TienThueDiLai.ToString(),
			     
				(this.TienDiLaiSauThue == null) ? string.Empty : this.TienDiLaiSauThue.ToString(),
			     
				this.HoanTat,
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKy columns.
	/// </summary>
	[Serializable]
	public enum ViewBangChietTinhGiangDayRaDeChamThiLan1NamHocHocKyColumn
	{
		/// <summary>
		/// MaQuanLy : 
		/// </summary>
		[EnumTextValue("MaQuanLy")]
		[ColumnEnum("MaQuanLy", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaQuanLy,
		/// <summary>
		/// MaLopHocPhan : 
		/// </summary>
		[EnumTextValue("MaLopHocPhan")]
		[ColumnEnum("MaLopHocPhan", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 30)]
		MaLopHocPhan,
		/// <summary>
		/// SoLuong : 
		/// </summary>
		[EnumTextValue("SoLuong")]
		[ColumnEnum("SoLuong", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SoLuong,
		/// <summary>
		/// TietGiangDay : 
		/// </summary>
		[EnumTextValue("TietGiangDay")]
		[ColumnEnum("TietGiangDay", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		TietGiangDay,
		/// <summary>
		/// HeSoLopDong : 
		/// </summary>
		[EnumTextValue("HeSoLopDong")]
		[ColumnEnum("HeSoLopDong", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		HeSoLopDong,
		/// <summary>
		/// SoBaiDaCham : 
		/// </summary>
		[EnumTextValue("SoBaiDaCham")]
		[ColumnEnum("SoBaiDaCham", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		SoBaiDaCham,
		/// <summary>
		/// SoDeThiDapAn : 
		/// </summary>
		[EnumTextValue("SoDeThiDapAn")]
		[ColumnEnum("SoDeThiDapAn", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		SoDeThiDapAn,
		/// <summary>
		/// MaLopSinhVien : 
		/// </summary>
		[EnumTextValue("MaLopSinhVien")]
		[ColumnEnum("MaLopSinhVien", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaLopSinhVien,
		/// <summary>
		/// TenLopSinhVien : 
		/// </summary>
		[EnumTextValue("TenLopSinhVien")]
		[ColumnEnum("TenLopSinhVien", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenLopSinhVien,
		/// <summary>
		/// HoTen : 
		/// </summary>
		[EnumTextValue("HoTen")]
		[ColumnEnum("HoTen", typeof(System.String), System.Data.DbType.String, false, false, true, 152)]
		HoTen,
		/// <summary>
		/// NoiLamViec : 
		/// </summary>
		[EnumTextValue("NoiLamViec")]
		[ColumnEnum("NoiLamViec", typeof(System.String), System.Data.DbType.String, false, false, false, 100)]
		NoiLamViec,
		/// <summary>
		/// MaCoSo : 
		/// </summary>
		[EnumTextValue("MaCoSo")]
		[ColumnEnum("MaCoSo", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaCoSo,
		/// <summary>
		/// TenCoSo : 
		/// </summary>
		[EnumTextValue("TenCoSo")]
		[ColumnEnum("TenCoSo", typeof(System.String), System.Data.DbType.String, false, false, false, 100)]
		TenCoSo,
		/// <summary>
		/// MaHocVi : 
		/// </summary>
		[EnumTextValue("MaHocVi")]
		[ColumnEnum("MaHocVi", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		MaHocVi,
		/// <summary>
		/// TenHocVi : 
		/// </summary>
		[EnumTextValue("TenHocVi")]
		[ColumnEnum("TenHocVi", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TenHocVi,
		/// <summary>
		/// MaHocHam : 
		/// </summary>
		[EnumTextValue("MaHocHam")]
		[ColumnEnum("MaHocHam", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		MaHocHam,
		/// <summary>
		/// TenHocHam : 
		/// </summary>
		[EnumTextValue("TenHocHam")]
		[ColumnEnum("TenHocHam", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TenHocHam,
		/// <summary>
		/// HeSoTinChi : 
		/// </summary>
		[EnumTextValue("HeSoTinChi")]
		[ColumnEnum("HeSoTinChi", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		HeSoTinChi,
		/// <summary>
		/// DonGiaMotTiet : 
		/// </summary>
		[EnumTextValue("DonGiaMotTiet")]
		[ColumnEnum("DonGiaMotTiet", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		DonGiaMotTiet,
		/// <summary>
		/// TienGiangDayTruocThue : 
		/// </summary>
		[EnumTextValue("TienGiangDayTruocThue")]
		[ColumnEnum("TienGiangDayTruocThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienGiangDayTruocThue,
		/// <summary>
		/// TienThueGiangDay : 
		/// </summary>
		[EnumTextValue("TienThueGiangDay")]
		[ColumnEnum("TienThueGiangDay", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienThueGiangDay,
		/// <summary>
		/// TienGiangDaySauThue : 
		/// </summary>
		[EnumTextValue("TienGiangDaySauThue")]
		[ColumnEnum("TienGiangDaySauThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienGiangDaySauThue,
		/// <summary>
		/// DonGiaChamThiChuan : 
		/// </summary>
		[EnumTextValue("DonGiaChamThiChuan")]
		[ColumnEnum("DonGiaChamThiChuan", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		DonGiaChamThiChuan,
		/// <summary>
		/// TienChamThiTruocThue : 
		/// </summary>
		[EnumTextValue("TienChamThiTruocThue")]
		[ColumnEnum("TienChamThiTruocThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienChamThiTruocThue,
		/// <summary>
		/// TienThueChamThi : 
		/// </summary>
		[EnumTextValue("TienThueChamThi")]
		[ColumnEnum("TienThueChamThi", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienThueChamThi,
		/// <summary>
		/// TienChamThiSauThue : 
		/// </summary>
		[EnumTextValue("TienChamThiSauThue")]
		[ColumnEnum("TienChamThiSauThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienChamThiSauThue,
		/// <summary>
		/// DonGiaRaDeThiChuan : 
		/// </summary>
		[EnumTextValue("DonGiaRaDeThiChuan")]
		[ColumnEnum("DonGiaRaDeThiChuan", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		DonGiaRaDeThiChuan,
		/// <summary>
		/// TienRaDeTruocThue : 
		/// </summary>
		[EnumTextValue("TienRaDeTruocThue")]
		[ColumnEnum("TienRaDeTruocThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienRaDeTruocThue,
		/// <summary>
		/// TienThueRaDe : 
		/// </summary>
		[EnumTextValue("TienThueRaDe")]
		[ColumnEnum("TienThueRaDe", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienThueRaDe,
		/// <summary>
		/// TienRaDeSauThue : 
		/// </summary>
		[EnumTextValue("TienRaDeSauThue")]
		[ColumnEnum("TienRaDeSauThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienRaDeSauThue,
		/// <summary>
		/// HocKy : 
		/// </summary>
		[EnumTextValue("HocKy")]
		[ColumnEnum("HocKy", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		HocKy,
		/// <summary>
		/// TenHocKy : 
		/// </summary>
		[EnumTextValue("TenHocKy")]
		[ColumnEnum("TenHocKy", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenHocKy,
		/// <summary>
		/// NamHoc : 
		/// </summary>
		[EnumTextValue("NamHoc")]
		[ColumnEnum("NamHoc", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		NamHoc,
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		[EnumTextValue("MaMonHoc")]
		[ColumnEnum("MaMonHoc", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaMonHoc,
		/// <summary>
		/// TenMonHoc : 
		/// </summary>
		[EnumTextValue("TenMonHoc")]
		[ColumnEnum("TenMonHoc", typeof(System.String), System.Data.DbType.String, false, false, false, 255)]
		TenMonHoc,
		/// <summary>
		/// TenLopHocPhan : 
		/// </summary>
		[EnumTextValue("TenLopHocPhan")]
		[ColumnEnum("TenLopHocPhan", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 30)]
		TenLopHocPhan,
		/// <summary>
		/// TenHocPhan : 
		/// </summary>
		[EnumTextValue("TenHocPhan")]
		[ColumnEnum("TenHocPhan", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		TenHocPhan,
		/// <summary>
		/// MaBacDaoTao : 
		/// </summary>
		[EnumTextValue("MaBacDaoTao")]
		[ColumnEnum("MaBacDaoTao", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaBacDaoTao,
		/// <summary>
		/// TenBacDaoTao : 
		/// </summary>
		[EnumTextValue("TenBacDaoTao")]
		[ColumnEnum("TenBacDaoTao", typeof(System.String), System.Data.DbType.String, false, false, false, 100)]
		TenBacDaoTao,
		/// <summary>
		/// MaHeDaoTao : 
		/// </summary>
		[EnumTextValue("MaHeDaoTao")]
		[ColumnEnum("MaHeDaoTao", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaHeDaoTao,
		/// <summary>
		/// TenHeDaoTao : 
		/// </summary>
		[EnumTextValue("TenHeDaoTao")]
		[ColumnEnum("TenHeDaoTao", typeof(System.String), System.Data.DbType.String, false, false, false, 100)]
		TenHeDaoTao,
		/// <summary>
		/// SoLanDiLai : 
		/// </summary>
		[EnumTextValue("SoLanDiLai")]
		[ColumnEnum("SoLanDiLai", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		SoLanDiLai,
		/// <summary>
		/// SoNgayLuuTru : 
		/// </summary>
		[EnumTextValue("SoNgayLuuTru")]
		[ColumnEnum("SoNgayLuuTru", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		SoNgayLuuTru,
		/// <summary>
		/// ChiPhiDiLai : 
		/// </summary>
		[EnumTextValue("ChiPhiDiLai")]
		[ColumnEnum("ChiPhiDiLai", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		ChiPhiDiLai,
		/// <summary>
		/// ChiPhiLuuTru : 
		/// </summary>
		[EnumTextValue("ChiPhiLuuTru")]
		[ColumnEnum("ChiPhiLuuTru", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		ChiPhiLuuTru,
		/// <summary>
		/// TienLuuTruTruocThue : 
		/// </summary>
		[EnumTextValue("TienLuuTruTruocThue")]
		[ColumnEnum("TienLuuTruTruocThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienLuuTruTruocThue,
		/// <summary>
		/// TienThueLuuTru : 
		/// </summary>
		[EnumTextValue("TienThueLuuTru")]
		[ColumnEnum("TienThueLuuTru", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienThueLuuTru,
		/// <summary>
		/// TienLuuTruSauThue : 
		/// </summary>
		[EnumTextValue("TienLuuTruSauThue")]
		[ColumnEnum("TienLuuTruSauThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienLuuTruSauThue,
		/// <summary>
		/// TienDiLaiTruocThue : 
		/// </summary>
		[EnumTextValue("TienDiLaiTruocThue")]
		[ColumnEnum("TienDiLaiTruocThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienDiLaiTruocThue,
		/// <summary>
		/// TienThueDiLai : 
		/// </summary>
		[EnumTextValue("TienThueDiLai")]
		[ColumnEnum("TienThueDiLai", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienThueDiLai,
		/// <summary>
		/// TienDiLaiSauThue : 
		/// </summary>
		[EnumTextValue("TienDiLaiSauThue")]
		[ColumnEnum("TienDiLaiSauThue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		TienDiLaiSauThue,
		/// <summary>
		/// HoanTat : 
		/// </summary>
		[EnumTextValue("HoanTat")]
		[ColumnEnum("HoanTat", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		HoanTat
	}//End enum

} // end namespace
