using System;
using System.ComponentModel;

namespace PMS.Entities
{
	/// <summary>
	///		The data structure representation of the 'GiangVienChoDuyetHoSo' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IGiangVienChoDuyetHoSo 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "GiangVienChoDuyetHoSo"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// MaDanToc : 
		/// </summary>
		System.String  MaDanToc  { get; set; }
		
		/// <summary>
		/// MaTonGiao : 
		/// </summary>
		System.String  MaTonGiao  { get; set; }
		
		/// <summary>
		/// MaDonVi : 
		/// </summary>
		System.String  MaDonVi  { get; set; }
		
		/// <summary>
		/// MaHocHam : 
		/// </summary>
		System.Int32?  MaHocHam  { get; set; }
		
		/// <summary>
		/// MaHocVi : 
		/// </summary>
		System.Int32?  MaHocVi  { get; set; }
		
		/// <summary>
		/// MaLoaiGiangVien : 
		/// </summary>
		System.Int32?  MaLoaiGiangVien  { get; set; }
		
		/// <summary>
		/// MaNguoiLap : 
		/// </summary>
		System.Int32?  MaNguoiLap  { get; set; }
		
		/// <summary>
		/// MatKhau : 
		/// </summary>
		System.String  MatKhau  { get; set; }
		
		/// <summary>
		/// MaTinhTrang : 
		/// </summary>
		System.Int32?  MaTinhTrang  { get; set; }
		
		/// <summary>
		/// MaQuanLy : 
		/// </summary>
		System.String  MaQuanLy  { get; set; }
		
		/// <summary>
		/// Ho : 
		/// </summary>
		System.String  Ho  { get; set; }
		
		/// <summary>
		/// TenDem : 
		/// </summary>
		System.String  TenDem  { get; set; }
		
		/// <summary>
		/// Ten : 
		/// </summary>
		System.String  Ten  { get; set; }
		
		/// <summary>
		/// NgaySinh : 
		/// </summary>
		System.String  NgaySinh  { get; set; }
		
		/// <summary>
		/// GioiTinh : 
		/// </summary>
		System.Boolean?  GioiTinh  { get; set; }
		
		/// <summary>
		/// NoiSinh : 
		/// </summary>
		System.String  NoiSinh  { get; set; }
		
		/// <summary>
		/// Cmnd : 
		/// </summary>
		System.String  Cmnd  { get; set; }
		
		/// <summary>
		/// NgayCap : 
		/// </summary>
		System.String  NgayCap  { get; set; }
		
		/// <summary>
		/// NoiCap : 
		/// </summary>
		System.String  NoiCap  { get; set; }
		
		/// <summary>
		/// DoanDang : 
		/// </summary>
		System.Boolean?  DoanDang  { get; set; }
		
		/// <summary>
		/// NgayVaoDoanDang : 
		/// </summary>
		System.String  NgayVaoDoanDang  { get; set; }
		
		/// <summary>
		/// NgayKyHopDong : 
		/// </summary>
		System.DateTime?  NgayKyHopDong  { get; set; }
		
		/// <summary>
		/// NgayKetThucHopDong : 
		/// </summary>
		System.DateTime?  NgayKetThucHopDong  { get; set; }
		
		/// <summary>
		/// HinhAnh : 
		/// </summary>
		System.Byte[]  HinhAnh  { get; set; }
		
		/// <summary>
		/// DiaChi : 
		/// </summary>
		System.String  DiaChi  { get; set; }
		
		/// <summary>
		/// ThuongTru : 
		/// </summary>
		System.String  ThuongTru  { get; set; }
		
		/// <summary>
		/// NoiLamViec : 
		/// </summary>
		System.String  NoiLamViec  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// DienThoai : 
		/// </summary>
		System.String  DienThoai  { get; set; }
		
		/// <summary>
		/// SoDiDong : 
		/// </summary>
		System.String  SoDiDong  { get; set; }
		
		/// <summary>
		/// SoTaiKhoan : 
		/// </summary>
		System.String  SoTaiKhoan  { get; set; }
		
		/// <summary>
		/// TenNganHang : 
		/// </summary>
		System.String  TenNganHang  { get; set; }
		
		/// <summary>
		/// MaSoThue : 
		/// </summary>
		System.String  MaSoThue  { get; set; }
		
		/// <summary>
		/// ChiNhanh : 
		/// </summary>
		System.String  ChiNhanh  { get; set; }
		
		/// <summary>
		/// SoSoBaoHiem : 
		/// </summary>
		System.String  SoSoBaoHiem  { get; set; }
		
		/// <summary>
		/// ThoiGianBatDau : 
		/// </summary>
		System.String  ThoiGianBatDau  { get; set; }
		
		/// <summary>
		/// BacLuong : 
		/// </summary>
		System.Decimal?  BacLuong  { get; set; }
		
		/// <summary>
		/// NgayHuongLuong : 
		/// </summary>
		System.String  NgayHuongLuong  { get; set; }
		
		/// <summary>
		/// NamLamViec : 
		/// </summary>
		System.String  NamLamViec  { get; set; }
		
		/// <summary>
		/// ChuyenNganh : 
		/// </summary>
		System.String  ChuyenNganh  { get; set; }
		
		/// <summary>
		/// MaHeSoThuLao : 
		/// </summary>
		System.String  MaHeSoThuLao  { get; set; }
		
		/// <summary>
		/// Ngach : 
		/// </summary>
		System.String  Ngach  { get; set; }
		
		/// <summary>
		/// SoHieuCongChuc : 
		/// </summary>
		System.String  SoHieuCongChuc  { get; set; }
		
		/// <summary>
		/// HRMID : 
		/// </summary>
		System.Guid?  Hrmid  { get; set; }
		
		/// <summary>
		/// NoiCapBang : 
		/// </summary>
		System.String  NoiCapBang  { get; set; }
		
		/// <summary>
		/// KhoaTaiKhoan : 
		/// </summary>
		System.Boolean?  KhoaTaiKhoan  { get; set; }
		
		/// <summary>
		/// MaLoaiNhanVien : 
		/// </summary>
		System.Int32?  MaLoaiNhanVien  { get; set; }
		
		/// <summary>
		/// MaNgachCongChuc : 
		/// </summary>
		System.Int32?  MaNgachCongChuc  { get; set; }
		
		/// <summary>
		/// MaTrinhDoChinhTri : 
		/// </summary>
		System.Int32?  MaTrinhDoChinhTri  { get; set; }
		
		/// <summary>
		/// MaTrinhDoSuPham : 
		/// </summary>
		System.Int32?  MaTrinhDoSuPham  { get; set; }
		
		/// <summary>
		/// MaTrinhDoNgoaiNgu : 
		/// </summary>
		System.Int32?  MaTrinhDoNgoaiNgu  { get; set; }
		
		/// <summary>
		/// MaTrinhDoTinHoc : 
		/// </summary>
		System.Int32?  MaTrinhDoTinHoc  { get; set; }
		
		/// <summary>
		/// MaTrinhDoQuanLyNhaNuoc : 
		/// </summary>
		System.Int32?  MaTrinhDoQuanLyNhaNuoc  { get; set; }
		
		/// <summary>
		/// NguoiCapNhat : 
		/// </summary>
		System.String  NguoiCapNhat  { get; set; }
		
		/// <summary>
		/// NgayCapNhat : 
		/// </summary>
		System.String  NgayCapNhat  { get; set; }
		
		/// <summary>
		/// KhoiKienThucGiangDay : 
		/// </summary>
		System.String  KhoiKienThucGiangDay  { get; set; }
		
		/// <summary>
		/// NganhDaoTao : 
		/// </summary>
		System.String  NganhDaoTao  { get; set; }
		
		/// <summary>
		/// DonViGiangDay : 
		/// </summary>
		System.String  DonViGiangDay  { get; set; }
		
		/// <summary>
		/// DaDuyet : 
		/// </summary>
		System.Boolean?  DaDuyet  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


