using System;
using System.ComponentModel;

namespace PMS.Entities
{
	/// <summary>
	///		The data structure representation of the 'KcqHeSoCoSo' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IKcqHeSoCoSo 
	{
		/// <summary>			
		/// MaHeSo : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "KcqHeSoCoSo"</remarks>
		System.Int32 MaHeSo { get; set; }
				
		
		
		/// <summary>
		/// MaQuanLy : 
		/// </summary>
		System.String  MaQuanLy  { get; set; }
		
		/// <summary>
		/// MaCoSo : 
		/// </summary>
		System.String  MaCoSo  { get; set; }
		
		/// <summary>
		/// HeSo : 
		/// </summary>
		System.Decimal?  HeSo  { get; set; }
		
		/// <summary>
		/// ThuTu : 
		/// </summary>
		System.Int32?  ThuTu  { get; set; }
		
		/// <summary>
		/// NgayBDApDung : 
		/// </summary>
		System.DateTime?  NgayBdApDung  { get; set; }
		
		/// <summary>
		/// NgayKTApDung : 
		/// </summary>
		System.DateTime?  NgayKtApDung  { get; set; }
		
		/// <summary>
		/// ThoiGianHoc : 
		/// </summary>
		System.String  ThoiGianHoc  { get; set; }
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		System.String  NamHoc  { get; set; }
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		System.String  HocKy  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


