using System;
using System.ComponentModel;

namespace PMS.Entities
{
	/// <summary>
	///		The data structure representation of the 'ThanhTraTheoThoiKhoaBieu' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IThanhTraTheoThoiKhoaBieu 
	{
		/// <summary>			
		/// MaLichHoc : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ThanhTraTheoThoiKhoaBieu"</remarks>
		System.Int32 MaLichHoc { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalMaLichHoc { get; set; }
			
		/// <summary>			
		/// MaCanBoGiangDay : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ThanhTraTheoThoiKhoaBieu"</remarks>
		System.String MaCanBoGiangDay { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalMaCanBoGiangDay { get; set; }
			
		
		
		/// <summary>
		/// MaViPham : 
		/// </summary>
		System.String  MaViPham  { get; set; }
		
		/// <summary>
		/// MaHinhThucViPhamHrm : 
		/// </summary>
		System.Guid?  MaHinhThucViPhamHrm  { get; set; }
		
		/// <summary>
		/// SiSo : 
		/// </summary>
		System.Int32?  SiSo  { get; set; }
		
		/// <summary>
		/// ThoiDiemGhiNhan : 
		/// </summary>
		System.String  ThoiDiemGhiNhan  { get; set; }
		
		/// <summary>
		/// LyDo : 
		/// </summary>
		System.String  LyDo  { get; set; }
		
		/// <summary>
		/// GhiChu : 
		/// </summary>
		System.String  GhiChu  { get; set; }
		
		/// <summary>
		/// NgayCapNhat : 
		/// </summary>
		System.String  NgayCapNhat  { get; set; }
		
		/// <summary>
		/// NguoiCapNhat : 
		/// </summary>
		System.String  NguoiCapNhat  { get; set; }
		
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		System.String  MaMonHoc  { get; set; }
		
		/// <summary>
		/// MaLopHocPhan : 
		/// </summary>
		System.String  MaLopHocPhan  { get; set; }
		
		/// <summary>
		/// SoTietGhiNhan : 
		/// </summary>
		System.Int32?  SoTietGhiNhan  { get; set; }
		
		/// <summary>
		/// Ngay : 
		/// </summary>
		System.String  Ngay  { get; set; }
		
		/// <summary>
		/// TietBatDau : 
		/// </summary>
		System.Int32?  TietBatDau  { get; set; }
		
		/// <summary>
		/// SoTiet : 
		/// </summary>
		System.Decimal?  SoTiet  { get; set; }
		
		/// <summary>
		/// Phong : 
		/// </summary>
		System.String  Phong  { get; set; }
		
		/// <summary>
		/// XacNhan : 
		/// </summary>
		System.Boolean?  XacNhan  { get; set; }
		
		/// <summary>
		/// SoTietQuyDoi : 
		/// </summary>
		System.Decimal?  SoTietQuyDoi  { get; set; }
		
		/// <summary>
		/// DaXacNhan : 
		/// </summary>
		System.Boolean?  DaXacNhan  { get; set; }
		
		/// <summary>
		/// ThanhLy : 
		/// </summary>
		System.String  ThanhLy  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


