
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file NghienCuuKhoaHoc.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'NghienCuuKhoaHoc' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class NghienCuuKhoaHocBase : EntityBase, INghienCuuKhoaHoc, IEntityId<NghienCuuKhoaHocKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private NghienCuuKhoaHocEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private NghienCuuKhoaHocEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private NghienCuuKhoaHocEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<NghienCuuKhoaHoc> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event NghienCuuKhoaHocEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event NghienCuuKhoaHocEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="NghienCuuKhoaHocBase"/> instance.
		///</summary>
		public NghienCuuKhoaHocBase()
		{
			this.entityData = new NghienCuuKhoaHocEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="NghienCuuKhoaHocBase"/> instance.
		///</summary>
		///<param name="_maGiangVien"></param>
		///<param name="_namHoc"></param>
		///<param name="_soTietDinhMuc"></param>
		///<param name="_soTietThucHien"></param>
		///<param name="_hocKy"></param>
		public NghienCuuKhoaHocBase(System.Int32? _maGiangVien, System.String _namHoc, 
			System.Decimal? _soTietDinhMuc, System.Decimal? _soTietThucHien, System.String _hocKy)
		{
			this.entityData = new NghienCuuKhoaHocEntityData();
			this.backupData = null;

			this.MaGiangVien = _maGiangVien;
			this.NamHoc = _namHoc;
			this.SoTietDinhMuc = _soTietDinhMuc;
			this.SoTietThucHien = _soTietThucHien;
			this.HocKy = _hocKy;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="NghienCuuKhoaHoc"/> instance.
		///</summary>
		///<param name="_maGiangVien"></param>
		///<param name="_namHoc"></param>
		///<param name="_soTietDinhMuc"></param>
		///<param name="_soTietThucHien"></param>
		///<param name="_hocKy"></param>
		public static NghienCuuKhoaHoc CreateNghienCuuKhoaHoc(System.Int32? _maGiangVien, System.String _namHoc, 
			System.Decimal? _soTietDinhMuc, System.Decimal? _soTietThucHien, System.String _hocKy)
		{
			NghienCuuKhoaHoc newNghienCuuKhoaHoc = new NghienCuuKhoaHoc();
			newNghienCuuKhoaHoc.MaGiangVien = _maGiangVien;
			newNghienCuuKhoaHoc.NamHoc = _namHoc;
			newNghienCuuKhoaHoc.SoTietDinhMuc = _soTietDinhMuc;
			newNghienCuuKhoaHoc.SoTietThucHien = _soTietThucHien;
			newNghienCuuKhoaHoc.HocKy = _hocKy;
			return newNghienCuuKhoaHoc;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaNghienCuuKhoaHoc property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 MaNghienCuuKhoaHoc
		{
			get
			{
				return this.entityData.MaNghienCuuKhoaHoc; 
			}
			
			set
			{
				if (this.entityData.MaNghienCuuKhoaHoc == value)
					return;
				
                OnPropertyChanging("MaNghienCuuKhoaHoc");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.MaNghienCuuKhoaHoc, this.entityData.MaNghienCuuKhoaHoc);
				this.entityData.MaNghienCuuKhoaHoc = value;
				this.EntityId.MaNghienCuuKhoaHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.MaNghienCuuKhoaHoc, this.entityData.MaNghienCuuKhoaHoc);
				OnPropertyChanged("MaNghienCuuKhoaHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaGiangVien property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? MaGiangVien
		{
			get
			{
				return this.entityData.MaGiangVien; 
			}
			
			set
			{
				if (this.entityData.MaGiangVien == value)
					return;
				
                OnPropertyChanging("MaGiangVien");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.MaGiangVien, this.entityData.MaGiangVien);
				this.entityData.MaGiangVien = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.MaGiangVien, this.entityData.MaGiangVien);
				OnPropertyChanged("MaGiangVien");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NamHoc property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String NamHoc
		{
			get
			{
				return this.entityData.NamHoc; 
			}
			
			set
			{
				if (this.entityData.NamHoc == value)
					return;
				
                OnPropertyChanging("NamHoc");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.NamHoc, this.entityData.NamHoc);
				this.entityData.NamHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.NamHoc, this.entityData.NamHoc);
				OnPropertyChanged("NamHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SoTietDinhMuc property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? SoTietDinhMuc
		{
			get
			{
				return this.entityData.SoTietDinhMuc; 
			}
			
			set
			{
				if (this.entityData.SoTietDinhMuc == value)
					return;
				
                OnPropertyChanging("SoTietDinhMuc");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.SoTietDinhMuc, this.entityData.SoTietDinhMuc);
				this.entityData.SoTietDinhMuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.SoTietDinhMuc, this.entityData.SoTietDinhMuc);
				OnPropertyChanged("SoTietDinhMuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SoTietThucHien property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? SoTietThucHien
		{
			get
			{
				return this.entityData.SoTietThucHien; 
			}
			
			set
			{
				if (this.entityData.SoTietThucHien == value)
					return;
				
                OnPropertyChanging("SoTietThucHien");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.SoTietThucHien, this.entityData.SoTietThucHien);
				this.entityData.SoTietThucHien = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.SoTietThucHien, this.entityData.SoTietThucHien);
				OnPropertyChanged("SoTietThucHien");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HocKy property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String HocKy
		{
			get
			{
				return this.entityData.HocKy; 
			}
			
			set
			{
				if (this.entityData.HocKy == value)
					return;
				
                OnPropertyChanging("HocKy");                    
				OnColumnChanging(NghienCuuKhoaHocColumn.HocKy, this.entityData.HocKy);
				this.entityData.HocKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(NghienCuuKhoaHocColumn.HocKy, this.entityData.HocKy);
				OnPropertyChanged("HocKy");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NamHoc", "Nam Hoc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HocKy", "Hoc Ky", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "NghienCuuKhoaHoc"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaNghienCuuKhoaHoc", "MaGiangVien", "NamHoc", "SoTietDinhMuc", "SoTietThucHien", "HocKy"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as NghienCuuKhoaHocEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (NghienCuuKhoaHoc) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<NghienCuuKhoaHoc>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as NghienCuuKhoaHoc);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed NghienCuuKhoaHoc Entity 
		///</summary>
		protected virtual NghienCuuKhoaHoc Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			NghienCuuKhoaHoc copy = new NghienCuuKhoaHoc();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MaNghienCuuKhoaHoc = this.MaNghienCuuKhoaHoc;
				copy.MaGiangVien = this.MaGiangVien;
				copy.NamHoc = this.NamHoc;
				copy.SoTietDinhMuc = this.SoTietDinhMuc;
				copy.SoTietThucHien = this.SoTietThucHien;
				copy.HocKy = this.HocKy;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed NghienCuuKhoaHoc Entity 
		///</summary>
		public virtual NghienCuuKhoaHoc Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed NghienCuuKhoaHoc Entity which is a deep copy of the current entity.
		///</summary>
		public virtual NghienCuuKhoaHoc DeepCopy()
		{
			return EntityHelper.Clone<NghienCuuKhoaHoc>(this as NghienCuuKhoaHoc);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as NghienCuuKhoaHocEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new NghienCuuKhoaHocEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as NghienCuuKhoaHocEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(NghienCuuKhoaHocColumn column)
		{
			switch(column)
			{
					case NghienCuuKhoaHocColumn.MaNghienCuuKhoaHoc:
					return entityData.MaNghienCuuKhoaHoc != _originalData.MaNghienCuuKhoaHoc;
					case NghienCuuKhoaHocColumn.MaGiangVien:
					return entityData.MaGiangVien != _originalData.MaGiangVien;
					case NghienCuuKhoaHocColumn.NamHoc:
					return entityData.NamHoc != _originalData.NamHoc;
					case NghienCuuKhoaHocColumn.SoTietDinhMuc:
					return entityData.SoTietDinhMuc != _originalData.SoTietDinhMuc;
					case NghienCuuKhoaHocColumn.SoTietThucHien:
					return entityData.SoTietThucHien != _originalData.SoTietThucHien;
					case NghienCuuKhoaHocColumn.HocKy:
					return entityData.HocKy != _originalData.HocKy;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< NghienCuuKhoaHocColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaNghienCuuKhoaHoc != _originalData.MaNghienCuuKhoaHoc;
			result = result || entityData.MaGiangVien != _originalData.MaGiangVien;
			result = result || entityData.NamHoc != _originalData.NamHoc;
			result = result || entityData.SoTietDinhMuc != _originalData.SoTietDinhMuc;
			result = result || entityData.SoTietThucHien != _originalData.SoTietThucHien;
			result = result || entityData.HocKy != _originalData.HocKy;
			return result;
		}	
		
		///<summary>
		///  Returns a NghienCuuKhoaHoc Entity with the original data.
		///</summary>
		public NghienCuuKhoaHoc GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateNghienCuuKhoaHoc(
				_originalData.MaGiangVien,
				_originalData.NamHoc,
				_originalData.SoTietDinhMuc,
				_originalData.SoTietThucHien,
				_originalData.HocKy
				);
				
			return (NghienCuuKhoaHoc)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="NghienCuuKhoaHocBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is NghienCuuKhoaHocBase)
				return ValueEquals(this, (NghienCuuKhoaHocBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="NghienCuuKhoaHocBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaNghienCuuKhoaHoc.GetHashCode() ^ 
					((this.MaGiangVien == null) ? string.Empty : this.MaGiangVien.ToString()).GetHashCode() ^ 
					((this.NamHoc == null) ? string.Empty : this.NamHoc.ToString()).GetHashCode() ^ 
					((this.SoTietDinhMuc == null) ? string.Empty : this.SoTietDinhMuc.ToString()).GetHashCode() ^ 
					((this.SoTietThucHien == null) ? string.Empty : this.SoTietThucHien.ToString()).GetHashCode() ^ 
					((this.HocKy == null) ? string.Empty : this.HocKy.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="NghienCuuKhoaHocBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(NghienCuuKhoaHocBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="NghienCuuKhoaHocBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="NghienCuuKhoaHocBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="NghienCuuKhoaHocBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(NghienCuuKhoaHocBase Object1, NghienCuuKhoaHocBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaNghienCuuKhoaHoc != Object2.MaNghienCuuKhoaHoc)
				equal = false;
			if ( Object1.MaGiangVien != null && Object2.MaGiangVien != null )
			{
				if (Object1.MaGiangVien != Object2.MaGiangVien)
					equal = false;
			}
			else if (Object1.MaGiangVien == null ^ Object2.MaGiangVien == null )
			{
				equal = false;
			}
			if ( Object1.NamHoc != null && Object2.NamHoc != null )
			{
				if (Object1.NamHoc != Object2.NamHoc)
					equal = false;
			}
			else if (Object1.NamHoc == null ^ Object2.NamHoc == null )
			{
				equal = false;
			}
			if ( Object1.SoTietDinhMuc != null && Object2.SoTietDinhMuc != null )
			{
				if (Object1.SoTietDinhMuc != Object2.SoTietDinhMuc)
					equal = false;
			}
			else if (Object1.SoTietDinhMuc == null ^ Object2.SoTietDinhMuc == null )
			{
				equal = false;
			}
			if ( Object1.SoTietThucHien != null && Object2.SoTietThucHien != null )
			{
				if (Object1.SoTietThucHien != Object2.SoTietThucHien)
					equal = false;
			}
			else if (Object1.SoTietThucHien == null ^ Object2.SoTietThucHien == null )
			{
				equal = false;
			}
			if ( Object1.HocKy != null && Object2.HocKy != null )
			{
				if (Object1.HocKy != Object2.HocKy)
					equal = false;
			}
			else if (Object1.HocKy == null ^ Object2.HocKy == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((NghienCuuKhoaHocBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static NghienCuuKhoaHocComparer GetComparer()
        {
            return new NghienCuuKhoaHocComparer();
        }
        */

        // Comparer delegates back to NghienCuuKhoaHoc
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(NghienCuuKhoaHoc rhs, NghienCuuKhoaHocColumn which)
        {
            switch (which)
            {
            	
            	
            	case NghienCuuKhoaHocColumn.MaNghienCuuKhoaHoc:
            		return this.MaNghienCuuKhoaHoc.CompareTo(rhs.MaNghienCuuKhoaHoc);
            		
            		                 
            	
            	
            	case NghienCuuKhoaHocColumn.MaGiangVien:
            		return this.MaGiangVien.Value.CompareTo(rhs.MaGiangVien.Value);
            		
            		                 
            	
            	
            	case NghienCuuKhoaHocColumn.NamHoc:
            		return this.NamHoc.CompareTo(rhs.NamHoc);
            		
            		                 
            	
            	
            	case NghienCuuKhoaHocColumn.SoTietDinhMuc:
            		return this.SoTietDinhMuc.Value.CompareTo(rhs.SoTietDinhMuc.Value);
            		
            		                 
            	
            	
            	case NghienCuuKhoaHocColumn.SoTietThucHien:
            		return this.SoTietThucHien.Value.CompareTo(rhs.SoTietThucHien.Value);
            		
            		                 
            	
            	
            	case NghienCuuKhoaHocColumn.HocKy:
            		return this.HocKy.CompareTo(rhs.HocKy);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<NghienCuuKhoaHocKey> Members
		
		// member variable for the EntityId property
		private NghienCuuKhoaHocKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual NghienCuuKhoaHocKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new NghienCuuKhoaHocKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("NghienCuuKhoaHoc")
					.Append("|").Append( this.MaNghienCuuKhoaHoc.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- MaNghienCuuKhoaHoc: {0}{6}- MaGiangVien: {1}{6}- NamHoc: {2}{6}- SoTietDinhMuc: {3}{6}- SoTietThucHien: {4}{6}- HocKy: {5}{6}{8}", 
				this.MaNghienCuuKhoaHoc,
				(this.MaGiangVien == null) ? string.Empty : this.MaGiangVien.ToString(),
				(this.NamHoc == null) ? string.Empty : this.NamHoc.ToString(),
				(this.SoTietDinhMuc == null) ? string.Empty : this.SoTietDinhMuc.ToString(),
				(this.SoTietThucHien == null) ? string.Empty : this.SoTietThucHien.ToString(),
				(this.HocKy == null) ? string.Empty : this.HocKy.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'NghienCuuKhoaHoc' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class NghienCuuKhoaHocEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MaNghienCuuKhoaHoc : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "NghienCuuKhoaHoc"</remarks>
		public System.Int32 MaNghienCuuKhoaHoc;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaGiangVien : 
		/// </summary>
		public System.Int32? MaGiangVien = null;
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		public System.String NamHoc = null;
		
		/// <summary>
		/// SoTietDinhMuc : 
		/// </summary>
		public System.Decimal? SoTietDinhMuc = null;
		
		/// <summary>
		/// SoTietThucHien : 
		/// </summary>
		public System.Decimal? SoTietThucHien = null;
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		public System.String HocKy = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			NghienCuuKhoaHocEntityData _tmp = new NghienCuuKhoaHocEntityData();
						
			_tmp.MaNghienCuuKhoaHoc = this.MaNghienCuuKhoaHoc;
			
			_tmp.MaGiangVien = this.MaGiangVien;
			_tmp.NamHoc = this.NamHoc;
			_tmp.SoTietDinhMuc = this.SoTietDinhMuc;
			_tmp.SoTietThucHien = this.SoTietThucHien;
			_tmp.HocKy = this.HocKy;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			NghienCuuKhoaHocEntityData _tmp = new NghienCuuKhoaHocEntityData();
						
			_tmp.MaNghienCuuKhoaHoc = this.MaNghienCuuKhoaHoc;
			
			_tmp.MaGiangVien = this.MaGiangVien;
			_tmp.NamHoc = this.NamHoc;
			_tmp.SoTietDinhMuc = this.SoTietDinhMuc;
			_tmp.SoTietThucHien = this.SoTietThucHien;
			_tmp.HocKy = this.HocKy;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="NghienCuuKhoaHocColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(NghienCuuKhoaHocColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="NghienCuuKhoaHocColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(NghienCuuKhoaHocColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="NghienCuuKhoaHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(NghienCuuKhoaHocColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				NghienCuuKhoaHocEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new NghienCuuKhoaHocEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="NghienCuuKhoaHocColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(NghienCuuKhoaHocColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				NghienCuuKhoaHocEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new NghienCuuKhoaHocEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region NghienCuuKhoaHocEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="NghienCuuKhoaHoc"/> object.
	/// </remarks>
	public class NghienCuuKhoaHocEventArgs : System.EventArgs
	{
		private NghienCuuKhoaHocColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the NghienCuuKhoaHocEventArgs class.
		///</summary>
		public NghienCuuKhoaHocEventArgs(NghienCuuKhoaHocColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the NghienCuuKhoaHocEventArgs class.
		///</summary>
		public NghienCuuKhoaHocEventArgs(NghienCuuKhoaHocColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The NghienCuuKhoaHocColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="NghienCuuKhoaHocColumn" />
		public NghienCuuKhoaHocColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all NghienCuuKhoaHoc related events.
	///</summary>
	public delegate void NghienCuuKhoaHocEventHandler(object sender, NghienCuuKhoaHocEventArgs e);
	
	#region NghienCuuKhoaHocComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class NghienCuuKhoaHocComparer : System.Collections.Generic.IComparer<NghienCuuKhoaHoc>
	{
		NghienCuuKhoaHocColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:NghienCuuKhoaHocComparer"/> class.
        /// </summary>
		public NghienCuuKhoaHocComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:NghienCuuKhoaHocComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public NghienCuuKhoaHocComparer(NghienCuuKhoaHocColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="NghienCuuKhoaHoc"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="NghienCuuKhoaHoc"/> to compare.</param>
        /// <param name="b">The second <c>NghienCuuKhoaHoc</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(NghienCuuKhoaHoc a, NghienCuuKhoaHoc b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(NghienCuuKhoaHoc entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(NghienCuuKhoaHoc a, NghienCuuKhoaHoc b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public NghienCuuKhoaHocColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region NghienCuuKhoaHocKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="NghienCuuKhoaHoc"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class NghienCuuKhoaHocKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the NghienCuuKhoaHocKey class.
		/// </summary>
		public NghienCuuKhoaHocKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the NghienCuuKhoaHocKey class.
		/// </summary>
		public NghienCuuKhoaHocKey(NghienCuuKhoaHocBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaNghienCuuKhoaHoc = entity.MaNghienCuuKhoaHoc;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the NghienCuuKhoaHocKey class.
		/// </summary>
		public NghienCuuKhoaHocKey(System.Int32 _maNghienCuuKhoaHoc)
		{
			#region Init Properties

			this.MaNghienCuuKhoaHoc = _maNghienCuuKhoaHoc;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private NghienCuuKhoaHocBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public NghienCuuKhoaHocBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaNghienCuuKhoaHoc property
		private System.Int32 _maNghienCuuKhoaHoc;
		
		/// <summary>
		/// Gets or sets the MaNghienCuuKhoaHoc property.
		/// </summary>
		public System.Int32 MaNghienCuuKhoaHoc
		{
			get { return _maNghienCuuKhoaHoc; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaNghienCuuKhoaHoc = value;
				
				_maNghienCuuKhoaHoc = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaNghienCuuKhoaHoc = ( values["MaNghienCuuKhoaHoc"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MaNghienCuuKhoaHoc"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaNghienCuuKhoaHoc", MaNghienCuuKhoaHoc);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaNghienCuuKhoaHoc: {0}{1}",
								MaNghienCuuKhoaHoc,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region NghienCuuKhoaHocColumn Enum
	
	/// <summary>
	/// Enumerate the NghienCuuKhoaHoc columns.
	/// </summary>
	[Serializable]
	public enum NghienCuuKhoaHocColumn : int
	{
		/// <summary>
		/// MaNghienCuuKhoaHoc : 
		/// </summary>
		[EnumTextValue("Ma Nghien Cuu Khoa Hoc")]
		[ColumnEnum("MaNghienCuuKhoaHoc", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		MaNghienCuuKhoaHoc = 1,
		/// <summary>
		/// MaGiangVien : 
		/// </summary>
		[EnumTextValue("Ma Giang Vien")]
		[ColumnEnum("MaGiangVien", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		MaGiangVien = 2,
		/// <summary>
		/// NamHoc : 
		/// </summary>
		[EnumTextValue("Nam Hoc")]
		[ColumnEnum("NamHoc", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		NamHoc = 3,
		/// <summary>
		/// SoTietDinhMuc : 
		/// </summary>
		[EnumTextValue("So Tiet Dinh Muc")]
		[ColumnEnum("SoTietDinhMuc", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		SoTietDinhMuc = 4,
		/// <summary>
		/// SoTietThucHien : 
		/// </summary>
		[EnumTextValue("So Tiet Thuc Hien")]
		[ColumnEnum("SoTietThucHien", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		SoTietThucHien = 5,
		/// <summary>
		/// HocKy : 
		/// </summary>
		[EnumTextValue("Hoc Ky")]
		[ColumnEnum("HocKy", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		HocKy = 6
	}//End enum

	#endregion NghienCuuKhoaHocColumn Enum

} // end namespace
