/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file VChiTietQuyDoiTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="VChiTietQuyDoi"/> objects (entity, collection and repository).
    /// </summary>
    public partial class VChiTietQuyDoiTest
    {
    	// the VChiTietQuyDoi instance used to test the repository.
		private VChiTietQuyDoi mock;
		
		// the VList<VChiTietQuyDoi> instance used to test the repository.
		private VList<VChiTietQuyDoi> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the VChiTietQuyDoi Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of VChiTietQuyDoi objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.VChiTietQuyDoiProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.VChiTietQuyDoiProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some VChiTietQuyDoi objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.VChiTietQuyDoiProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.VChiTietQuyDoiProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock VChiTietQuyDoi entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_VChiTietQuyDoi.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VChiTietQuyDoi)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock VChiTietQuyDoi entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_VChiTietQuyDoi.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VChiTietQuyDoi)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (VChiTietQuyDoi) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a VChiTietQuyDoi collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_VChiTietQuyDoiCollection.xml";
		
			VList<VChiTietQuyDoi> mockCollection = new VList<VChiTietQuyDoi>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<VChiTietQuyDoi>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<VChiTietQuyDoi> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a VChiTietQuyDoi collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_VChiTietQuyDoiCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<VChiTietQuyDoi>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<VChiTietQuyDoi> mockCollection = (VList<VChiTietQuyDoi>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<VChiTietQuyDoi> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed VChiTietQuyDoi Entity with mock values.
		///</summary>
		static public VChiTietQuyDoi CreateMockInstance()
		{		
			VChiTietQuyDoi mock = new VChiTietQuyDoi();
						
			mock.MaKhoa = TestUtility.Instance.RandomString(9, false);;
			mock.TenKhoa = TestUtility.Instance.RandomString(126, false);;
			mock.MaBoMon = TestUtility.Instance.RandomString(9, false);;
			mock.TenBoMon = TestUtility.Instance.RandomString(126, false);;
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.SoTiet1 = (decimal)TestUtility.Instance.RandomShort();
			mock.TietDoAn1 = (decimal)TestUtility.Instance.RandomShort();
			mock.SoTiet2 = (decimal)TestUtility.Instance.RandomShort();
			mock.TietDoAn2 = (decimal)TestUtility.Instance.RandomShort();
		   return (VChiTietQuyDoi)mock;
		}
		

		#endregion
    }
}
