
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ViewPhuTroiTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="ViewPhuTroi"/> objects (entity, collection and repository).
    /// </summary>
    public partial class ViewPhuTroiTest
    {
    	// the ViewPhuTroi instance used to test the repository.
		private ViewPhuTroi mock;
		
		// the VList<ViewPhuTroi> instance used to test the repository.
		private VList<ViewPhuTroi> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the ViewPhuTroi Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of ViewPhuTroi objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.ViewPhuTroiProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.ViewPhuTroiProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some ViewPhuTroi objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.ViewPhuTroiProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.ViewPhuTroiProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock ViewPhuTroi entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_ViewPhuTroi.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(ViewPhuTroi)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock ViewPhuTroi entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_ViewPhuTroi.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(ViewPhuTroi)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (ViewPhuTroi) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a ViewPhuTroi collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_ViewPhuTroiCollection.xml";
		
			VList<ViewPhuTroi> mockCollection = new VList<ViewPhuTroi>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<ViewPhuTroi>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<ViewPhuTroi> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a ViewPhuTroi collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_ViewPhuTroiCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<ViewPhuTroi>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<ViewPhuTroi> mockCollection = (VList<ViewPhuTroi>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<ViewPhuTroi> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed ViewPhuTroi Entity with mock values.
		///</summary>
		static public ViewPhuTroi CreateMockInstance()
		{		
			ViewPhuTroi mock = new ViewPhuTroi();
						
			mock.MaCauHinhChotGio = TestUtility.Instance.RandomNumber();
			mock.MaGiangVien = TestUtility.Instance.RandomString(14, false);;
			mock.MaChotGio = TestUtility.Instance.RandomNumber();
			mock.HoTen = TestUtility.Instance.RandomString(75, false);;
			mock.MaKhoa = TestUtility.Instance.RandomString(20, false);;
			mock.MaBoMon = TestUtility.Instance.RandomString(20, false);;
			mock.TenKhoa = TestUtility.Instance.RandomString(126, false);;
			mock.TenBoMon = TestUtility.Instance.RandomString(126, false);;
			mock.MaLoaiGiangVien = TestUtility.Instance.RandomNumber();
			mock.TenLoaiGiangVien = TestUtility.Instance.RandomString(49, false);;
			mock.MaBacDaoTao = TestUtility.Instance.RandomString(20, false);;
			mock.MaHeDaoTao = TestUtility.Instance.RandomString(20, false);;
			mock.TuNgay = TestUtility.Instance.RandomDateTime();
			mock.DenNgay = TestUtility.Instance.RandomDateTime();
			mock.TenQuanLy = TestUtility.Instance.RandomString(49, false);;
			mock.MaChucVu = TestUtility.Instance.RandomString(20, false);;
			mock.TenChucVu = TestUtility.Instance.RandomString(99, false);;
			mock.TietNghiaVu = TestUtility.Instance.RandomNumber();
			mock.Nckh = (decimal)TestUtility.Instance.RandomShort();
			mock.NhiemVuKhac = (decimal)TestUtility.Instance.RandomShort();
			mock.GioChuan = (decimal)TestUtility.Instance.RandomShort();
			mock.TietThucDayCd = (decimal)TestUtility.Instance.RandomShort();
			mock.TietThucDayTc = (decimal)TestUtility.Instance.RandomShort();
			mock.TietQuyDoiCd = (decimal)TestUtility.Instance.RandomShort();
			mock.TietQuyDoiTc = (decimal)TestUtility.Instance.RandomShort();
			mock.TcQuyDoi = (decimal)TestUtility.Instance.RandomShort();
		   return (ViewPhuTroi)mock;
		}
		

		#endregion
    }
}
