/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file VTongHopKhoiLuongTest.cs instead.
*/
#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="VTongHopKhoiLuong"/> objects (entity, collection and repository).
    /// </summary>
    public partial class VTongHopKhoiLuongTest
    {
    	// the VTongHopKhoiLuong instance used to test the repository.
		private VTongHopKhoiLuong mock;
		
		// the VList<VTongHopKhoiLuong> instance used to test the repository.
		private VList<VTongHopKhoiLuong> mockCollection;		

        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>
        static private void Init_Generated()
        {
			System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the VTongHopKhoiLuong Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
        static private void CleanUp_Generated()
        {       	
			System.Console.WriteLine();
			System.Console.WriteLine();
        }
		
		/// <summary>
		/// Selects a page of VTongHopKhoiLuong objects from the database.
		/// </summary>
		private void Step_1_SelectAll_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.VTongHopKhoiLuongProvider.GetPaged(null, 0, 10, out count);
			Assert.IsTrue(count >= 0, "Select Query Failed with GetPaged");
			System.Console.WriteLine("DataRepository.VTongHopKhoiLuongProvider.GetPaged():");			
			System.Console.WriteLine(mockCollection);			
		}
		
		/// <summary>
		/// Searches some VTongHopKhoiLuong objects from the database.
		/// </summary>
		private void Step_2_Search_Generated()
		{
			int count = -1;
			mockCollection = DataRepository.VTongHopKhoiLuongProvider.Find(null, null, "", 0, 10, out count);
			Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
			
			System.Console.WriteLine("DataRepository.VTongHopKhoiLuongProvider.Find():");			
			System.Console.WriteLine(mockCollection);
					
		}
		 //Find
			
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock VTongHopKhoiLuong entity into a temporary file.
		/// </summary>
		private void Step_6_SerializeEntity_Generated()
		{
			string fileName = "temp_VTongHopKhoiLuong.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VTongHopKhoiLuong)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mock); 
			myWriter.Close();
			System.Console.WriteLine("mock correctly serialized to a temporary file.");			
		}
		
		/// <summary>
		/// Deserialize the mock VTongHopKhoiLuong entity from a temporary file.
		/// </summary>
		private void Step_7_DeserializeEntity_Generated()
		{
			string fileName = "temp_VTongHopKhoiLuong.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VTongHopKhoiLuong)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			mock = (VTongHopKhoiLuong) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a VTongHopKhoiLuong collection into a temporary file.
		/// </summary>
		private void Step_8_SerializeCollection_Generated()
		{
			string fileName = "temp_VTongHopKhoiLuongCollection.xml";
		
			VList<VTongHopKhoiLuong> mockCollection = new VList<VTongHopKhoiLuong>();
			mockCollection.Add(mock);
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<VTongHopKhoiLuong>)); 
			System.IO.StreamWriter myWriter = new System.IO.StreamWriter(fileName); 
			mySerializer.Serialize(myWriter, mockCollection); 
			myWriter.Close();
			
			System.Console.WriteLine("VList<VTongHopKhoiLuong> correctly serialized to a temporary file.");					
		}
		
		
		/// <summary>
		/// Deserialize a VTongHopKhoiLuong collection from a temporary file.
		/// </summary>
		private void Step_9_DeserializeCollection_Generated()
		{
			string fileName = "temp_VTongHopKhoiLuongCollection.xml";
		
			XmlSerializer mySerializer = new XmlSerializer(typeof(VList<VTongHopKhoiLuong>)); 
			System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open); 
			VList<VTongHopKhoiLuong> mockCollection = (VList<VTongHopKhoiLuong>) mySerializer.Deserialize(myFileStream);
			myFileStream.Close();
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("VList<VTongHopKhoiLuong> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		#region Mock Instance
		///<summary>
		///  Returns a Typed VTongHopKhoiLuong Entity with mock values.
		///</summary>
		static public VTongHopKhoiLuong CreateMockInstance()
		{		
			VTongHopKhoiLuong mock = new VTongHopKhoiLuong();
						
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.MaKhoa = TestUtility.Instance.RandomString(9, false);;
			mock.TenKhoa = TestUtility.Instance.RandomString(126, false);;
			mock.LyThuyet1 = (decimal)TestUtility.Instance.RandomShort();
			mock.ThucHanh1 = (decimal)TestUtility.Instance.RandomShort();
			mock.ThiNghiem1 = (decimal)TestUtility.Instance.RandomShort();
			mock.DoAn1 = (decimal)TestUtility.Instance.RandomShort();
			mock.LyThuyet2 = (decimal)TestUtility.Instance.RandomShort();
			mock.ThucHanh2 = (decimal)TestUtility.Instance.RandomShort();
			mock.ThiNghiem2 = (decimal)TestUtility.Instance.RandomShort();
			mock.DoAn2 = (decimal)TestUtility.Instance.RandomShort();
		   return (VTongHopKhoiLuong)mock;
		}
		

		#endregion
    }
}
