
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file HeSoThamNienTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;
using PMS.Data.Bases;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="HeSoThamNien"/> objects (entity, collection and repository).
    /// </summary>
   public partial class HeSoThamNienTest
    {
    	// the HeSoThamNien instance used to test the repository.
		protected HeSoThamNien mock;
		
		// the TList<HeSoThamNien> instance used to test the repository.
		protected TList<HeSoThamNien> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the HeSoThamNien Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock HeSoThamNien entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.HeSoThamNienProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.HeSoThamNienProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all HeSoThamNien objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.HeSoThamNienProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.HeSoThamNienProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.HeSoThamNienProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all HeSoThamNien children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.HeSoThamNienProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.HeSoThamNienProvider.DeepLoading += new EntityProviderBaseCore<HeSoThamNien, HeSoThamNienKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.HeSoThamNienProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("HeSoThamNien instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.HeSoThamNienProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock HeSoThamNien entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				HeSoThamNien mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.HeSoThamNienProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.HeSoThamNienProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.HeSoThamNienProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock HeSoThamNien entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (HeSoThamNien)CreateMockInstance(tm);
				DataRepository.HeSoThamNienProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.HeSoThamNienProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.HeSoThamNienProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock HeSoThamNien entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HeSoThamNien.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock HeSoThamNien entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HeSoThamNien.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<HeSoThamNien>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a HeSoThamNien collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HeSoThamNienCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<HeSoThamNien> mockCollection = new TList<HeSoThamNien>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<HeSoThamNien> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a HeSoThamNien collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_HeSoThamNienCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<HeSoThamNien>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<HeSoThamNien> mockCollection = (TList<HeSoThamNien>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<HeSoThamNien> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				HeSoThamNien entity = CreateMockInstance(tm);
				bool result = DataRepository.HeSoThamNienProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				HeSoThamNien entity = CreateMockInstance(tm);
				bool result = DataRepository.HeSoThamNienProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				HeSoThamNien t0 = DataRepository.HeSoThamNienProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				HeSoThamNien entity = mock.Copy() as HeSoThamNien;
				entity = (HeSoThamNien)mock.Clone();
				Assert.IsTrue(HeSoThamNien.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				HeSoThamNien mock = CreateMockInstance(tm);
				bool result = DataRepository.HeSoThamNienProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				HeSoThamNienQuery query = new HeSoThamNienQuery();
			
				query.AppendEquals(HeSoThamNienColumn.Id, mock.Id.ToString());
				if(mock.TuNam != null)
					query.AppendEquals(HeSoThamNienColumn.TuNam, mock.TuNam.ToString());
				if(mock.DenNam != null)
					query.AppendEquals(HeSoThamNienColumn.DenNam, mock.DenNam.ToString());
				if(mock.HeSo != null)
					query.AppendEquals(HeSoThamNienColumn.HeSo, mock.HeSo.ToString());
				if(mock.GhiChu != null)
					query.AppendEquals(HeSoThamNienColumn.GhiChu, mock.GhiChu.ToString());
				if(mock.NgayCapNhat != null)
					query.AppendEquals(HeSoThamNienColumn.NgayCapNhat, mock.NgayCapNhat.ToString());
				if(mock.NguoiCapNhat != null)
					query.AppendEquals(HeSoThamNienColumn.NguoiCapNhat, mock.NguoiCapNhat.ToString());
				
				TList<HeSoThamNien> results = DataRepository.HeSoThamNienProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed HeSoThamNien Entity with mock values.
		///</summary>
		static public HeSoThamNien CreateMockInstance_Generated(TransactionManager tm)
		{		
			HeSoThamNien mock = new HeSoThamNien();
						
			mock.TuNam = (decimal)TestUtility.Instance.RandomShort();
			mock.DenNam = (decimal)TestUtility.Instance.RandomShort();
			mock.HeSo = (decimal)TestUtility.Instance.RandomShort();
			mock.GhiChu = TestUtility.Instance.RandomString(249, false);;
			mock.NgayCapNhat = TestUtility.Instance.RandomDateTime();
			mock.NguoiCapNhat = TestUtility.Instance.RandomString(24, false);;
			
		
			// create a temporary collection and add the item to it
			TList<HeSoThamNien> tempMockCollection = new TList<HeSoThamNien>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (HeSoThamNien)mock;
		}
		
		
		///<summary>
		///  Update the Typed HeSoThamNien Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, HeSoThamNien mock)
		{
			mock.TuNam = (decimal)TestUtility.Instance.RandomShort();
			mock.DenNam = (decimal)TestUtility.Instance.RandomShort();
			mock.HeSo = (decimal)TestUtility.Instance.RandomShort();
			mock.GhiChu = TestUtility.Instance.RandomString(249, false);;
			mock.NgayCapNhat = TestUtility.Instance.RandomDateTime();
			mock.NguoiCapNhat = TestUtility.Instance.RandomString(24, false);;
			
		}
		#endregion
    }
}
