
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file UteThanhToanThuLaoTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;
using PMS.Data.Bases;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="UteThanhToanThuLao"/> objects (entity, collection and repository).
    /// </summary>
   public partial class UteThanhToanThuLaoTest
    {
    	// the UteThanhToanThuLao instance used to test the repository.
		protected UteThanhToanThuLao mock;
		
		// the TList<UteThanhToanThuLao> instance used to test the repository.
		protected TList<UteThanhToanThuLao> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the UteThanhToanThuLao Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock UteThanhToanThuLao entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.UteThanhToanThuLaoProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.UteThanhToanThuLaoProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all UteThanhToanThuLao objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.UteThanhToanThuLaoProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.UteThanhToanThuLaoProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.UteThanhToanThuLaoProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all UteThanhToanThuLao children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.UteThanhToanThuLaoProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.UteThanhToanThuLaoProvider.DeepLoading += new EntityProviderBaseCore<UteThanhToanThuLao, UteThanhToanThuLaoKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.UteThanhToanThuLaoProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("UteThanhToanThuLao instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.UteThanhToanThuLaoProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock UteThanhToanThuLao entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				UteThanhToanThuLao mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.UteThanhToanThuLaoProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.UteThanhToanThuLaoProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.UteThanhToanThuLaoProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock UteThanhToanThuLao entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (UteThanhToanThuLao)CreateMockInstance(tm);
				DataRepository.UteThanhToanThuLaoProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.UteThanhToanThuLaoProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.UteThanhToanThuLaoProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock UteThanhToanThuLao entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_UteThanhToanThuLao.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock UteThanhToanThuLao entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_UteThanhToanThuLao.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<UteThanhToanThuLao>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a UteThanhToanThuLao collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_UteThanhToanThuLaoCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<UteThanhToanThuLao> mockCollection = new TList<UteThanhToanThuLao>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<UteThanhToanThuLao> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a UteThanhToanThuLao collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_UteThanhToanThuLaoCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<UteThanhToanThuLao>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<UteThanhToanThuLao> mockCollection = (TList<UteThanhToanThuLao>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<UteThanhToanThuLao> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				UteThanhToanThuLao entity = CreateMockInstance(tm);
				bool result = DataRepository.UteThanhToanThuLaoProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				UteThanhToanThuLao entity = CreateMockInstance(tm);
				bool result = DataRepository.UteThanhToanThuLaoProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				UteThanhToanThuLao t0 = DataRepository.UteThanhToanThuLaoProvider.GetByIdKhoiLuongQuyDoi(tm, entity.IdKhoiLuongQuyDoi);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				UteThanhToanThuLao entity = mock.Copy() as UteThanhToanThuLao;
				entity = (UteThanhToanThuLao)mock.Clone();
				Assert.IsTrue(UteThanhToanThuLao.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				UteThanhToanThuLao mock = CreateMockInstance(tm);
				bool result = DataRepository.UteThanhToanThuLaoProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				UteThanhToanThuLaoQuery query = new UteThanhToanThuLaoQuery();
			
				query.AppendEquals(UteThanhToanThuLaoColumn.IdKhoiLuongQuyDoi, mock.IdKhoiLuongQuyDoi.ToString());
				if(mock.MaMonHoc != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaMonHoc, mock.MaMonHoc.ToString());
				if(mock.TenMonHoc != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.TenMonHoc, mock.TenMonHoc.ToString());
				if(mock.NhomMonHoc != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.NhomMonHoc, mock.NhomMonHoc.ToString());
				if(mock.NamHoc != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.NamHoc, mock.NamHoc.ToString());
				if(mock.HocKy != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.HocKy, mock.HocKy.ToString());
				if(mock.MaLopHocPhan != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaLopHocPhan, mock.MaLopHocPhan.ToString());
				if(mock.Nhom != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.Nhom, mock.Nhom.ToString());
				if(mock.MaLop != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaLop, mock.MaLop.ToString());
				if(mock.SoTinChi != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SoTinChi, mock.SoTinChi.ToString());
				if(mock.SoTiet != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SoTiet, mock.SoTiet.ToString());
				if(mock.SiSo != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SiSo, mock.SiSo.ToString());
				if(mock.LopClc != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.LopClc, mock.LopClc.ToString());
				if(mock.SoTietDayChuNhat != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SoTietDayChuNhat, mock.SoTietDayChuNhat.ToString());
				if(mock.MaLoaiHocPhan != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaLoaiHocPhan, mock.MaLoaiHocPhan.ToString());
				if(mock.HeSoLopDongLyThuyet != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.HeSoLopDongLyThuyet, mock.HeSoLopDongLyThuyet.ToString());
				if(mock.HeSoLopDongThTnTt != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.HeSoLopDongThTnTt, mock.HeSoLopDongThTnTt.ToString());
				if(mock.MaQuanLy != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaQuanLy, mock.MaQuanLy.ToString());
				if(mock.Ho != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.Ho, mock.Ho.ToString());
				if(mock.Ten != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.Ten, mock.Ten.ToString());
				if(mock.HoTen != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.HoTen, mock.HoTen.ToString());
				if(mock.MaHocHam != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaHocHam, mock.MaHocHam.ToString());
				if(mock.MaHocVi != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaHocVi, mock.MaHocVi.ToString());
				if(mock.MaLoaiGiangVien != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaLoaiGiangVien, mock.MaLoaiGiangVien.ToString());
				if(mock.MaDonVi != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.MaDonVi, mock.MaDonVi.ToString());
				if(mock.DonGia != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.DonGia, mock.DonGia.ToString());
				if(mock.TietQuyDoi != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.TietQuyDoi, mock.TietQuyDoi.ToString());
				if(mock.ThanhTienDayChuNhat != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.ThanhTienDayChuNhat, mock.ThanhTienDayChuNhat.ToString());
				if(mock.ThanhTien != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.ThanhTien, mock.ThanhTien.ToString());
				if(mock.TongThanhTien != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.TongThanhTien, mock.TongThanhTien.ToString());
				if(mock.NgayCapNhat != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.NgayCapNhat, mock.NgayCapNhat.ToString());
				if(mock.DaChot != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.DaChot, mock.DaChot.ToString());
				if(mock.HeSoHocKy != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.HeSoHocKy, mock.HeSoHocKy.ToString());
				if(mock.SoGioThucGiangTrenLop != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SoGioThucGiangTrenLop, mock.SoGioThucGiangTrenLop.ToString());
				if(mock.SoGioChuanTinhThem != null)
					query.AppendEquals(UteThanhToanThuLaoColumn.SoGioChuanTinhThem, mock.SoGioChuanTinhThem.ToString());
				
				TList<UteThanhToanThuLao> results = DataRepository.UteThanhToanThuLaoProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed UteThanhToanThuLao Entity with mock values.
		///</summary>
		static public UteThanhToanThuLao CreateMockInstance_Generated(TransactionManager tm)
		{		
			UteThanhToanThuLao mock = new UteThanhToanThuLao();
						
			mock.MaMonHoc = TestUtility.Instance.RandomString(9, false);;
			mock.TenMonHoc = TestUtility.Instance.RandomString(249, false);;
			mock.NhomMonHoc = TestUtility.Instance.RandomString(9, false);;
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.MaLopHocPhan = TestUtility.Instance.RandomString(24, false);;
			mock.Nhom = TestUtility.Instance.RandomString(24, false);;
			mock.MaLop = TestUtility.Instance.RandomString(99, false);;
			mock.SoTinChi = TestUtility.Instance.RandomNumber();
			mock.SoTiet = TestUtility.Instance.RandomNumber();
			mock.SiSo = TestUtility.Instance.RandomNumber();
			mock.LopClc = TestUtility.Instance.RandomBoolean();
			mock.SoTietDayChuNhat = TestUtility.Instance.RandomNumber();
			mock.MaLoaiHocPhan = TestUtility.Instance.RandomNumber();
			mock.HeSoLopDongLyThuyet = (decimal)TestUtility.Instance.RandomShort();
			mock.HeSoLopDongThTnTt = (decimal)TestUtility.Instance.RandomShort();
			mock.MaQuanLy = TestUtility.Instance.RandomString(9, false);;
			mock.Ho = TestUtility.Instance.RandomString(24, false);;
			mock.Ten = TestUtility.Instance.RandomString(24, false);;
			mock.HoTen = TestUtility.Instance.RandomString(49, false);;
			mock.MaHocHam = TestUtility.Instance.RandomNumber();
			mock.MaHocVi = TestUtility.Instance.RandomNumber();
			mock.MaLoaiGiangVien = TestUtility.Instance.RandomNumber();
			mock.MaDonVi = TestUtility.Instance.RandomString(9, false);;
			mock.DonGia = (decimal)TestUtility.Instance.RandomShort();
			mock.TietQuyDoi = (decimal)TestUtility.Instance.RandomShort();
			mock.ThanhTienDayChuNhat = (decimal)TestUtility.Instance.RandomShort();
			mock.ThanhTien = (decimal)TestUtility.Instance.RandomShort();
			mock.TongThanhTien = (decimal)TestUtility.Instance.RandomShort();
			mock.NgayCapNhat = TestUtility.Instance.RandomDateTime();
			mock.DaChot = TestUtility.Instance.RandomBoolean();
			mock.HeSoHocKy = (decimal)TestUtility.Instance.RandomShort();
			mock.SoGioThucGiangTrenLop = (decimal)TestUtility.Instance.RandomShort();
			mock.SoGioChuanTinhThem = (decimal)TestUtility.Instance.RandomShort();
			
			//OneToOneRelationship
			UteKhoiLuongQuyDoi mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi = UteKhoiLuongQuyDoiTest.CreateMockInstance(tm);
			DataRepository.UteKhoiLuongQuyDoiProvider.Insert(tm, mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi);
			mock.IdKhoiLuongQuyDoi = mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi.Id;
		
			// create a temporary collection and add the item to it
			TList<UteThanhToanThuLao> tempMockCollection = new TList<UteThanhToanThuLao>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (UteThanhToanThuLao)mock;
		}
		
		
		///<summary>
		///  Update the Typed UteThanhToanThuLao Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, UteThanhToanThuLao mock)
		{
			mock.MaMonHoc = TestUtility.Instance.RandomString(9, false);;
			mock.TenMonHoc = TestUtility.Instance.RandomString(249, false);;
			mock.NhomMonHoc = TestUtility.Instance.RandomString(9, false);;
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.MaLopHocPhan = TestUtility.Instance.RandomString(24, false);;
			mock.Nhom = TestUtility.Instance.RandomString(24, false);;
			mock.MaLop = TestUtility.Instance.RandomString(99, false);;
			mock.SoTinChi = TestUtility.Instance.RandomNumber();
			mock.SoTiet = TestUtility.Instance.RandomNumber();
			mock.SiSo = TestUtility.Instance.RandomNumber();
			mock.LopClc = TestUtility.Instance.RandomBoolean();
			mock.SoTietDayChuNhat = TestUtility.Instance.RandomNumber();
			mock.MaLoaiHocPhan = TestUtility.Instance.RandomNumber();
			mock.HeSoLopDongLyThuyet = (decimal)TestUtility.Instance.RandomShort();
			mock.HeSoLopDongThTnTt = (decimal)TestUtility.Instance.RandomShort();
			mock.MaQuanLy = TestUtility.Instance.RandomString(9, false);;
			mock.Ho = TestUtility.Instance.RandomString(24, false);;
			mock.Ten = TestUtility.Instance.RandomString(24, false);;
			mock.HoTen = TestUtility.Instance.RandomString(49, false);;
			mock.MaHocHam = TestUtility.Instance.RandomNumber();
			mock.MaHocVi = TestUtility.Instance.RandomNumber();
			mock.MaLoaiGiangVien = TestUtility.Instance.RandomNumber();
			mock.MaDonVi = TestUtility.Instance.RandomString(9, false);;
			mock.DonGia = (decimal)TestUtility.Instance.RandomShort();
			mock.TietQuyDoi = (decimal)TestUtility.Instance.RandomShort();
			mock.ThanhTienDayChuNhat = (decimal)TestUtility.Instance.RandomShort();
			mock.ThanhTien = (decimal)TestUtility.Instance.RandomShort();
			mock.TongThanhTien = (decimal)TestUtility.Instance.RandomShort();
			mock.NgayCapNhat = TestUtility.Instance.RandomDateTime();
			mock.DaChot = TestUtility.Instance.RandomBoolean();
			mock.HeSoHocKy = (decimal)TestUtility.Instance.RandomShort();
			mock.SoGioThucGiangTrenLop = (decimal)TestUtility.Instance.RandomShort();
			mock.SoGioChuanTinhThem = (decimal)TestUtility.Instance.RandomShort();
			
			//OneToOneRelationship
			UteKhoiLuongQuyDoi mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi = UteKhoiLuongQuyDoiTest.CreateMockInstance(tm);
			DataRepository.UteKhoiLuongQuyDoiProvider.Insert(tm, mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi);
			mock.IdKhoiLuongQuyDoi = mockUteKhoiLuongQuyDoiByIdKhoiLuongQuyDoi.Id;
					
		}
		#endregion
    }
}
