/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file SqlBangPhuTroiGioDayGiangVienProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using PMS.Entities;
using PMS.Data;
using PMS.Data.Bases;

#endregion

namespace PMS.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="BangPhuTroiGioDayGiangVien"/> entity.
	///</summary>
	public abstract partial class SqlBangPhuTroiGioDayGiangVienProviderBase : BangPhuTroiGioDayGiangVienProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlBangPhuTroiGioDayGiangVienProviderBase"/> instance.
		/// </summary>
		public SqlBangPhuTroiGioDayGiangVienProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlBangPhuTroiGioDayGiangVienProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we should use stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlBangPhuTroiGioDayGiangVienProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="_maGiangVien">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Int32 _maGiangVien)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@MaGiangVien", DbType.Int32, _maGiangVien);
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Delete")); 

			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(BangPhuTroiGioDayGiangVien)
					,_maGiangVien);
                EntityManager.StopTracking(entityKey);
                
			}
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Delete")); 

			commandWrapper = null;
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND).</remarks>
		/// <returns>Returns a typed collection of PMS.Entities.BangPhuTroiGioDayGiangVien objects.</returns>
		public override TList<BangPhuTroiGioDayGiangVien> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new TList<BangPhuTroiGioDayGiangVien>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@MaGiangVien", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaQuanLy", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Ho", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Ten", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@NamHoc", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaDonVi", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TenDonVi", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@MaLoaiGiangVien", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TenLoaiGiangVien", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TcThucDay", DbType.Decimal, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TietQd", DbType.Decimal, DBNull.Value);
		database.AddInParameter(commandWrapper, "@NhiemVuGd", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@NhiemVuNckh", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@PhanCongCn", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CongTrinhCd", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CongTrinhTc", DbType.Int32, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("magiangvien ") || clause.Trim().StartsWith("magiangvien="))
				{
					database.SetParameterValue(commandWrapper, "@MaGiangVien", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("maquanly ") || clause.Trim().StartsWith("maquanly="))
				{
					database.SetParameterValue(commandWrapper, "@MaQuanLy", 
						clause.Trim().Remove(0,8).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ho ") || clause.Trim().StartsWith("ho="))
				{
					database.SetParameterValue(commandWrapper, "@Ho", 
						clause.Trim().Remove(0,2).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("ten ") || clause.Trim().StartsWith("ten="))
				{
					database.SetParameterValue(commandWrapper, "@Ten", 
						clause.Trim().Remove(0,3).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("namhoc ") || clause.Trim().StartsWith("namhoc="))
				{
					database.SetParameterValue(commandWrapper, "@NamHoc", 
						clause.Trim().Remove(0,6).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("madonvi ") || clause.Trim().StartsWith("madonvi="))
				{
					database.SetParameterValue(commandWrapper, "@MaDonVi", 
						clause.Trim().Remove(0,7).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tendonvi ") || clause.Trim().StartsWith("tendonvi="))
				{
					database.SetParameterValue(commandWrapper, "@TenDonVi", 
						clause.Trim().Remove(0,8).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("maloaigiangvien ") || clause.Trim().StartsWith("maloaigiangvien="))
				{
					database.SetParameterValue(commandWrapper, "@MaLoaiGiangVien", 
						clause.Trim().Remove(0,15).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tenloaigiangvien ") || clause.Trim().StartsWith("tenloaigiangvien="))
				{
					database.SetParameterValue(commandWrapper, "@TenLoaiGiangVien", 
						clause.Trim().Remove(0,16).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tcthucday ") || clause.Trim().StartsWith("tcthucday="))
				{
					database.SetParameterValue(commandWrapper, "@TcThucDay", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("tietqd ") || clause.Trim().StartsWith("tietqd="))
				{
					database.SetParameterValue(commandWrapper, "@TietQd", 
						clause.Trim().Remove(0,6).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("nhiemvugd ") || clause.Trim().StartsWith("nhiemvugd="))
				{
					database.SetParameterValue(commandWrapper, "@NhiemVuGd", 
						clause.Trim().Remove(0,9).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("nhiemvunckh ") || clause.Trim().StartsWith("nhiemvunckh="))
				{
					database.SetParameterValue(commandWrapper, "@NhiemVuNckh", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("phancongcn ") || clause.Trim().StartsWith("phancongcn="))
				{
					database.SetParameterValue(commandWrapper, "@PhanCongCn", 
						clause.Trim().Remove(0,10).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("congtrinhcd ") || clause.Trim().StartsWith("congtrinhcd="))
				{
					database.SetParameterValue(commandWrapper, "@CongTrinhCd", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("congtrinhtc ") || clause.Trim().StartsWith("congtrinhtc="))
				{
					database.SetParameterValue(commandWrapper, "@CongTrinhTc", 
						clause.Trim().Remove(0,11).Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			TList<BangPhuTroiGioDayGiangVien> rows = new TList<BangPhuTroiGioDayGiangVien>();
	
				
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if (reader != null) 
					reader.Close();	
					
				commandWrapper = null;
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of PMS.Entities.BangPhuTroiGioDayGiangVien objects.</returns>
		public override TList<BangPhuTroiGioDayGiangVien> Find(TransactionManager transactionManager, IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlFilterParameterCollection filter = null;
			
			if (parameters == null)
				filter = new SqlFilterParameterCollection();
			else 
				filter = parameters.GetParameters();
				
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Find_Dynamic", typeof(BangPhuTroiGioDayGiangVienColumn), filter, orderBy, start, pageLength);
		
			SqlFilterParameter param;

			for ( int i = 0; i < filter.Count; i++ )
			{
				param = filter[i];
				database.AddInParameter(commandWrapper, param.Name, param.DbType, param.GetValue());
			}

			TList<BangPhuTroiGioDayGiangVien> rows = new TList<BangPhuTroiGioDayGiangVien>();
			IDataReader reader = null;
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "Find", rows)); 

				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "Find", rows)); 
			}
			finally
			{
				if ( reader != null )
					reader.Close();
					
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of PMS.Entities.BangPhuTroiGioDayGiangVien objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override TList<BangPhuTroiGioDayGiangVien> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			TList<BangPhuTroiGioDayGiangVien> rows = new TList<BangPhuTroiGioDayGiangVien>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
					
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetAll", rows)); 
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;	
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of PMS.Entities.BangPhuTroiGioDayGiangVien objects.</returns>
		public override TList<BangPhuTroiGioDayGiangVien> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_GetPaged", _useStoredProcedure);
		
			
            if (commandWrapper.CommandType == CommandType.Text
                && commandWrapper.CommandText != null)
            {
                commandWrapper.CommandText = commandWrapper.CommandText.Replace(SqlUtil.PAGE_INDEX, string.Concat(SqlUtil.PAGE_INDEX, Guid.NewGuid().ToString("N").Substring(0, 8)));
            }
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			TList<BangPhuTroiGioDayGiangVien> rows = new TList<BangPhuTroiGioDayGiangVien>();
			
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetPaged", rows)); 

			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
				
				commandWrapper = null;
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions
	#endregion
	
		#region Get By Index Functions

		#region GetByMaGiangVien
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_BangPhuTroiGioDay_GiangVien index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="_maGiangVien"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query.</param>
		/// <returns>Returns an instance of the <see cref="PMS.Entities.BangPhuTroiGioDayGiangVien"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override PMS.Entities.BangPhuTroiGioDayGiangVien GetByMaGiangVien(TransactionManager transactionManager, System.Int32 _maGiangVien, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_GetByMaGiangVien", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@MaGiangVien", DbType.Int32, _maGiangVien);
			
			IDataReader reader = null;
			TList<BangPhuTroiGioDayGiangVien> tmp = new TList<BangPhuTroiGioDayGiangVien>();
			try
			{
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetByMaGiangVien", tmp)); 

				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetByMaGiangVien", tmp));
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
					
				commandWrapper = null;
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk insert many entities to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the PMS.Entities.BangPhuTroiGioDayGiangVien object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<PMS.Entities.BangPhuTroiGioDayGiangVien> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "BangPhuTroiGioDay_GiangVien";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("MaGiangVien", typeof(System.Int32));
			col0.AllowDBNull = false;		
			DataColumn col1 = dataTable.Columns.Add("MaQuanLy", typeof(System.String));
			col1.AllowDBNull = false;		
			DataColumn col2 = dataTable.Columns.Add("Ho", typeof(System.String));
			col2.AllowDBNull = true;		
			DataColumn col3 = dataTable.Columns.Add("Ten", typeof(System.String));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("NamHoc", typeof(System.String));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("MaDonVi", typeof(System.String));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("TenDonVi", typeof(System.String));
			col6.AllowDBNull = false;		
			DataColumn col7 = dataTable.Columns.Add("MaLoaiGiangVien", typeof(System.Int32));
			col7.AllowDBNull = false;		
			DataColumn col8 = dataTable.Columns.Add("TenLoaiGiangVien", typeof(System.String));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("TCThucDay", typeof(System.Decimal));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("TietQD", typeof(System.Decimal));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("NhiemVuGD", typeof(System.Int32));
			col11.AllowDBNull = true;		
			DataColumn col12 = dataTable.Columns.Add("NhiemVuNCKH", typeof(System.Int32));
			col12.AllowDBNull = true;		
			DataColumn col13 = dataTable.Columns.Add("PhanCongCN", typeof(System.Int32));
			col13.AllowDBNull = true;		
			DataColumn col14 = dataTable.Columns.Add("CongTrinhCD", typeof(System.Int32));
			col14.AllowDBNull = true;		
			DataColumn col15 = dataTable.Columns.Add("CongTrinhTC", typeof(System.Int32));
			col15.AllowDBNull = true;		
			
			bulkCopy.ColumnMappings.Add("MaGiangVien", "MaGiangVien");
			bulkCopy.ColumnMappings.Add("MaQuanLy", "MaQuanLy");
			bulkCopy.ColumnMappings.Add("Ho", "Ho");
			bulkCopy.ColumnMappings.Add("Ten", "Ten");
			bulkCopy.ColumnMappings.Add("NamHoc", "NamHoc");
			bulkCopy.ColumnMappings.Add("MaDonVi", "MaDonVi");
			bulkCopy.ColumnMappings.Add("TenDonVi", "TenDonVi");
			bulkCopy.ColumnMappings.Add("MaLoaiGiangVien", "MaLoaiGiangVien");
			bulkCopy.ColumnMappings.Add("TenLoaiGiangVien", "TenLoaiGiangVien");
			bulkCopy.ColumnMappings.Add("TCThucDay", "TCThucDay");
			bulkCopy.ColumnMappings.Add("TietQD", "TietQD");
			bulkCopy.ColumnMappings.Add("NhiemVuGD", "NhiemVuGD");
			bulkCopy.ColumnMappings.Add("NhiemVuNCKH", "NhiemVuNCKH");
			bulkCopy.ColumnMappings.Add("PhanCongCN", "PhanCongCN");
			bulkCopy.ColumnMappings.Add("CongTrinhCD", "CongTrinhCD");
			bulkCopy.ColumnMappings.Add("CongTrinhTC", "CongTrinhTC");
			
			foreach(PMS.Entities.BangPhuTroiGioDayGiangVien entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["MaGiangVien"] = entity.MaGiangVien;
							
				
					row["MaQuanLy"] = entity.MaQuanLy;
							
				
					row["Ho"] = entity.Ho;
							
				
					row["Ten"] = entity.Ten;
							
				
					row["NamHoc"] = entity.NamHoc;
							
				
					row["MaDonVi"] = entity.MaDonVi;
							
				
					row["TenDonVi"] = entity.TenDonVi;
							
				
					row["MaLoaiGiangVien"] = entity.MaLoaiGiangVien;
							
				
					row["TenLoaiGiangVien"] = entity.TenLoaiGiangVien;
							
				
					row["TCThucDay"] = entity.TcThucDay.HasValue ? (object) entity.TcThucDay  : System.DBNull.Value;
							
				
					row["TietQD"] = entity.TietQd.HasValue ? (object) entity.TietQd  : System.DBNull.Value;
							
				
					row["NhiemVuGD"] = entity.NhiemVuGd.HasValue ? (object) entity.NhiemVuGd  : System.DBNull.Value;
							
				
					row["NhiemVuNCKH"] = entity.NhiemVuNckh.HasValue ? (object) entity.NhiemVuNckh  : System.DBNull.Value;
							
				
					row["PhanCongCN"] = entity.PhanCongCn.HasValue ? (object) entity.PhanCongCn  : System.DBNull.Value;
							
				
					row["CongTrinhCD"] = entity.CongTrinhCd.HasValue ? (object) entity.CongTrinhCd  : System.DBNull.Value;
							
				
					row["CongTrinhTC"] = entity.CongTrinhTc.HasValue ? (object) entity.CongTrinhTc  : System.DBNull.Value;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(PMS.Entities.BangPhuTroiGioDayGiangVien entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a PMS.Entities.BangPhuTroiGioDayGiangVien object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">PMS.Entities.BangPhuTroiGioDayGiangVien object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the PMS.Entities.BangPhuTroiGioDayGiangVien object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, PMS.Entities.BangPhuTroiGioDayGiangVien entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Insert", _useStoredProcedure);
			
            database.AddInParameter(commandWrapper, "@MaGiangVien", DbType.Int32, entity.MaGiangVien );
            database.AddInParameter(commandWrapper, "@MaQuanLy", DbType.AnsiString, entity.MaQuanLy );
            database.AddInParameter(commandWrapper, "@Ho", DbType.String, entity.Ho );
            database.AddInParameter(commandWrapper, "@Ten", DbType.String, entity.Ten );
            database.AddInParameter(commandWrapper, "@NamHoc", DbType.AnsiString, entity.NamHoc );
            database.AddInParameter(commandWrapper, "@MaDonVi", DbType.AnsiString, entity.MaDonVi );
            database.AddInParameter(commandWrapper, "@TenDonVi", DbType.String, entity.TenDonVi );
            database.AddInParameter(commandWrapper, "@MaLoaiGiangVien", DbType.Int32, entity.MaLoaiGiangVien );
            database.AddInParameter(commandWrapper, "@TenLoaiGiangVien", DbType.String, entity.TenLoaiGiangVien );
			database.AddInParameter(commandWrapper, "@TcThucDay", DbType.Decimal, (entity.TcThucDay.HasValue ? (object) entity.TcThucDay  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@TietQd", DbType.Decimal, (entity.TietQd.HasValue ? (object) entity.TietQd  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@NhiemVuGd", DbType.Int32, (entity.NhiemVuGd.HasValue ? (object) entity.NhiemVuGd  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@NhiemVuNckh", DbType.Int32, (entity.NhiemVuNckh.HasValue ? (object) entity.NhiemVuNckh  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@PhanCongCn", DbType.Int32, (entity.PhanCongCn.HasValue ? (object) entity.PhanCongCn  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@CongTrinhCd", DbType.Int32, (entity.CongTrinhCd.HasValue ? (object) entity.CongTrinhCd  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@CongTrinhTc", DbType.Int32, (entity.CongTrinhTc.HasValue ? (object) entity.CongTrinhTc  : System.DBNull.Value));
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Insert", entity));
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					
			
			entity.OriginalMaGiangVien = entity.MaGiangVien;
			
			entity.AcceptChanges();
	
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Insert", entity));

			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">PMS.Entities.BangPhuTroiGioDayGiangVien object to update.</param>
		/// <remarks>
		///		After updating the datasource, the PMS.Entities.BangPhuTroiGioDayGiangVien object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, PMS.Entities.BangPhuTroiGioDayGiangVien entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.sp_BangPhuTroiGioDay_GiangVien_Update", _useStoredProcedure);
			
            database.AddInParameter(commandWrapper, "@MaGiangVien", DbType.Int32, entity.MaGiangVien );
			database.AddInParameter(commandWrapper, "@OriginalMaGiangVien", DbType.Int32, entity.OriginalMaGiangVien);
            database.AddInParameter(commandWrapper, "@MaQuanLy", DbType.AnsiString, entity.MaQuanLy );
            database.AddInParameter(commandWrapper, "@Ho", DbType.String, entity.Ho );
            database.AddInParameter(commandWrapper, "@Ten", DbType.String, entity.Ten );
            database.AddInParameter(commandWrapper, "@NamHoc", DbType.AnsiString, entity.NamHoc );
            database.AddInParameter(commandWrapper, "@MaDonVi", DbType.AnsiString, entity.MaDonVi );
            database.AddInParameter(commandWrapper, "@TenDonVi", DbType.String, entity.TenDonVi );
            database.AddInParameter(commandWrapper, "@MaLoaiGiangVien", DbType.Int32, entity.MaLoaiGiangVien );
            database.AddInParameter(commandWrapper, "@TenLoaiGiangVien", DbType.String, entity.TenLoaiGiangVien );
			database.AddInParameter(commandWrapper, "@TcThucDay", DbType.Decimal, (entity.TcThucDay.HasValue ? (object) entity.TcThucDay : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@TietQd", DbType.Decimal, (entity.TietQd.HasValue ? (object) entity.TietQd : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@NhiemVuGd", DbType.Int32, (entity.NhiemVuGd.HasValue ? (object) entity.NhiemVuGd : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@NhiemVuNckh", DbType.Int32, (entity.NhiemVuNckh.HasValue ? (object) entity.NhiemVuNckh : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@PhanCongCn", DbType.Int32, (entity.PhanCongCn.HasValue ? (object) entity.PhanCongCn : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@CongTrinhCd", DbType.Int32, (entity.CongTrinhCd.HasValue ? (object) entity.CongTrinhCd : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@CongTrinhTc", DbType.Int32, (entity.CongTrinhTc.HasValue ? (object) entity.CongTrinhTc : System.DBNull.Value) );
			
			int results = 0;
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "Update", entity));

			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
            {
                EntityManager.StopTracking(entity.EntityTrackingKey);				
            }
			
			entity.OriginalMaGiangVien = entity.MaGiangVien;
			
			entity.AcceptChanges();
			
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "Update", entity));

			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	

		#region cust_BangPhuTroiGioDay_GiangVien_GetByNamHocHocKyMaDonViMaLoaiGiangVien
					
		/// <summary>
		///	This method wraps the 'cust_BangPhuTroiGioDay_GiangVien_GetByNamHocHocKyMaDonViMaLoaiGiangVien' stored procedure. 
		/// </summary>	
		/// <param name="namHoc"> A <c>System.String</c> instance.</param>
		/// <param name="maLoaiGv"> A <c>System.Int32</c> instance.</param>
		/// <param name="maDonVi"> A <c>System.String</c> instance.</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object.</param>
		/// <remark>This method is generated from a stored procedure.</remark>
		/// <returns>A <see cref="TList&lt;BangPhuTroiGioDayGiangVien&gt;"/> instance.</returns>
		public override TList<BangPhuTroiGioDayGiangVien> GetByNamHocHocKyMaDonViMaLoaiGiangVien(TransactionManager transactionManager, int start, int pageLength , System.String namHoc, System.Int32 maLoaiGv, System.String maDonVi)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.cust_BangPhuTroiGioDay_GiangVien_GetByNamHocHocKyMaDonViMaLoaiGiangVien", true);
			
			database.AddInParameter(commandWrapper, "@NamHoc", DbType.AnsiString,  namHoc );
			database.AddInParameter(commandWrapper, "@MaLoaiGV", DbType.Int32,  maLoaiGv );
			database.AddInParameter(commandWrapper, "@MaDonVi", DbType.AnsiString,  maDonVi );
	
			
			IDataReader reader = null;
			
			//Create Collection
				TList<BangPhuTroiGioDayGiangVien> rows = new TList<BangPhuTroiGioDayGiangVien>();
				//Provider Data Requesting Command Event
				OnDataRequesting(new CommandEventArgs(commandWrapper, "GetByNamHocHocKyMaDonViMaLoaiGiangVien", rows));
	
				if (transactionManager != null)
				{	
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}	
				
				try
				{    
					Fill(reader, rows, start, pageLength);
				}
				finally
				{
					if (reader != null) 
						reader.Close();
				}
				
				//Provider Data Requested Command Event
				OnDataRequested(new CommandEventArgs(commandWrapper, "GetByNamHocHocKyMaDonViMaLoaiGiangVien", rows));


				return rows;
		}
		#endregion

		#region cust_BangPhuTroiGioDay_GiangVien_DongBo
					
		/// <summary>
		///	This method wraps the 'cust_BangPhuTroiGioDay_GiangVien_DongBo' stored procedure. 
		/// </summary>	
		/// <param name="xmlData"> A <c>System.String</c> instance.</param>
		/// <param name="namHoc"> A <c>System.String</c> instance.</param>
		/// <param name="maLoaiGv"> A <c>System.Int32</c> instance.</param>
		/// <param name="maDonVi"> A <c>System.String</c> instance.</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object.</param>
		/// <remark>This method is generated from a stored procedure.</remark>
		public override void DongBo(TransactionManager transactionManager, int start, int pageLength , System.String xmlData, System.String namHoc, System.Int32 maLoaiGv, System.String maDonVi)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.cust_BangPhuTroiGioDay_GiangVien_DongBo", true);
			
			database.AddInParameter(commandWrapper, "@XmlData", DbType.Xml,  xmlData );
			database.AddInParameter(commandWrapper, "@NamHoc", DbType.AnsiString,  namHoc );
			database.AddInParameter(commandWrapper, "@MaLoaiGV", DbType.Int32,  maLoaiGv );
			database.AddInParameter(commandWrapper, "@MaDonVi", DbType.AnsiString,  maDonVi );
	
			
			//Provider Data Requesting Command Event
			OnDataRequesting(new CommandEventArgs(commandWrapper, "DongBo", (IEntity)null));

			if (transactionManager != null)
			{	
				Utility.ExecuteNonQuery(transactionManager, commandWrapper );
			}
			else
			{
				Utility.ExecuteNonQuery(database, commandWrapper);
			}
						
			//Provider Data Requested Command Event
			OnDataRequested(new CommandEventArgs(commandWrapper, "DongBo", (IEntity)null));


				
				return;
		}
		#endregion
		#endregion
	}//end class
} // end namespace
